### ISSUE TITLE
emtpy lines on saved replies

### ISSUE THREAD

**Issue by mokkin** [freescout-helpdesk/freescout#2596] opened 2023-01-20 09:14 UTC
Save replies insert an empty line at the beginning and the end of the text, but those are not in the template:

![Peek 2023-01-20 10-12](https://user-images.githubusercontent.com/2938748/213658651-01fcbfa6-6a4f-43d8-bea9-33f7c763ace5.gif)

**Comment by freescout-helpdesk** [comment] 2023-01-20 09:21
Duplicate of https://github.com/freescout-helpdesk/freescout/issues/1061

**Closed by freescout-helpdesk** 2023-01-20 09:21 UTC
