### ISSUE TITLE
Note > Change customer > Reply: does not send reply

### ISSUE THREAD

**Issue by fulldecent** [freescout-helpdesk/freescout#2953] opened 2023-04-27 13:43 UTC
_We are using API module in this scenario but I'm not sure if that is relevant to the bug._

# Test case

1. Create a conversation which is a phone note where the customer is a name+phone number (we did this step using API)
2. Change customer to a customer that includes an email address
3. Click reply to customer
4. Enter message, click send

# Expected outcome

Message goes to customer

# Actual outcome

Note is created

<img width="1622" alt="Screenshot 2023-04-27 at 09 37 27" src="https://user-images.githubusercontent.com/382183/234879933-d2977c21-70d8-43d2-b1cf-30c880c5e4cc.png">

---

We also created a full video walkthrough showing this. I emailed it to you directly at the freescout.helpdesk email address. You can find it in your email by searching this issue number or the magic word **a91834ff**.

**Comment by fulldecent** [comment] 2023-04-27 13:52
Ping @debbiepacmed

**Comment by freescout-helpdesk** [comment] 2023-04-28 05:18
We can't reproduce the issue. Can you give an API request body for the Step 1.

**Comment by freescout-helpdesk** [comment] 2023-05-05 05:53
Fixed in the `master` branch and will be released in the next release.

**Closed** 2023-05-06 04:58 UTC
