### ISSUE TITLE
freescout slow chnage refresh rate 

### ISSUE THREAD

**Issue by sainiaj** [freescout-helpdesk/freescout#2426] opened 2022-11-28 19:01 UTC
Hi i would like to change the refresh rate to be under 1 minute,

for example yellow/red banner is very slow at updating
email sent and fetch process is also very slow

I would like to change it to update few seconds 

is that possible 

Thank you

**Comment by freescout-helpdesk** [comment] 2022-11-30 06:50
Duplicate of https://github.com/freescout-helpdesk/freescout/issues/2425

**Closed by freescout-helpdesk** 2022-11-30 06:50 UTC
