### ISSUE TITLE
Time Tracking showing -1 instead of actual time

### ISSUE THREAD

**Issue by netspear** [freescout-helpdesk/freescout#2115] opened 2022-07-25 21:02 UTC
I have FreeScout installed on a Virtual Linux server. And everything is working great except the time tracker.

It seems to behave perfectly until I'm closing a ticket. 
Regardless of the amount of time its tracked, when I go to close the ticket it shows -1 : -1 : -1 as the total time. 
I tried Uninstalling a Deleting the Module then Reinstalling it. But I get the same results.

App Version 1.8.20
Web Server: nginx/1.18.0
PHP Version: PHP 8.1.2

**Comment by freescout-helpdesk** [comment] 2022-07-26 04:10
Could you please send a screenshot.

**Comment by netspear** [comment] 2022-07-26 04:18
Before I close the Ticket:
![B4](https://user-images.githubusercontent.com/99109793/180922005-293845e0-954d-4cf3-b613-ac73cb4b340a.png)

When I want to Close the Ticket:
![After](https://user-images.githubusercontent.com/99109793/180922050-6a76bcbd-3920-46c6-8407-1bd34e4a6f70.png)

Once The Ticket is Closed:
![After closed](https://user-images.githubusercontent.com/99109793/180922067-c14ae8f3-abf7-4c52-80d8-88d84d25a478.png)

**Comment by netspear** [comment] 2022-07-29 03:55
Hey, Just checking in, Would anyone be able to help me?

**Comment by freescout-helpdesk** [comment] 2022-08-01 09:24
We can't reproduce the issue.
Can you reproduce the issue on demo.freescout.net?
Are you using any non-official modules?

**Comment by netspear** [comment] 2022-08-01 19:06
I was able to reproduce the error on the demo website.
No, I am not running any non-official modules.
Please see attached screenshot.

Basically, if the timer is paused and I close the ticket, I get the issue.
If the timer is playing and I close the ticket, then I don't

![Screenshot 2022-08-01 150358](https://user-images.githubusercontent.com/99109793/182226040-c6c1fa1d-4a6b-4d19-b0e2-aa085cf53896.png)

**Comment by freescout-helpdesk** [comment] 2022-08-02 05:56
Fixed in Time Tracking Module v1.0.9

**Closed by freescout-helpdesk** 2022-08-02 05:56 UTC

**Comment by netspear** [comment] 2022-08-02 11:31
Thank you!!!
