### ISSUE TITLE
Blacklist is not taken into account when spam email is received as reply

### ISSUE THREAD

**Issue by boehmgui** [freescout-helpdesk/freescout#3178] opened 2023-07-12 12:46 UTC
FreeScout version: 1.8.84
Spam Module: 1.0.19

We have received a spam email, which we marked as spam and blacklisted the sender's address.
Now the spammer continues to send spam messages by replying to his own messages. Regardless of the fact that the sender's email address is blacklisted, these messages change the ticket status from spam to unassigned, i.e. the blacklist is not taken into account.

**Comment by freescout-helpdesk** [comment] 2023-07-12 13:09
It's by design.

**Comment by boehmgui** [comment] 2023-07-12 14:09
What is the point of blacklisting then? If I blacklisted a sender I did it on purpose and don't want to receive any email, no?

**Comment by freescout-helpdesk** [comment] 2023-07-13 06:59
Fixed in Spam Filter Module v1.0.20. Now If blacklisted customer or domain replies to a conversation marked as Spam its status will not be changed to Active.

**Closed by freescout-helpdesk** 2023-07-13 06:59 UTC
