### ISSUE TITLE
Calendar ICS file not imported

### ISSUE THREAD

**Issue by joris85** [freescout-helpdesk/freescout#1003] opened 2021-01-15 16:13 UTC
Hi guys,

From this mail the ICS file is not imported.
https://www.dropbox.com/sh/0fex06wah227kai/AABjR9bKbLjJ2tLXw3b_iQ0ma?dl=0

**Comment by freescout-helpdesk** [comment] 2021-01-23 13:48
What does it mean?

**Comment by joris85** [comment] 2021-01-30 08:08
Sorry did not see the question. 
when i get an invite (Google or crm) with a calendar file ics i do not get the file.

**Comment by freescout-helpdesk** [comment] 2021-01-30 08:58
Still the issue is not clear.

**Comment by joris85** [comment] 2021-02-25 17:06
I tested it and looks like it is working now.

ICS files where not shown in freescout as attachment (like when you attend an event and google sends you notification and file to add it to your agenda)

**Comment by freescout-helpdesk** [comment] 2022-06-18 14:57
Duplicate of https://github.com/freescout-helpdesk/freescout/issues/1412

**Closed by freescout-helpdesk** 2022-06-18 14:57 UTC
Labels: help wanted
