### ISSUE TITLE
iOS App margins bad alignment

### ISSUE THREAD

**Issue by myde2001** [freescout-helpdesk/freescout#3484] opened 2023-10-30 15:06 UTC
The iOS App margins are bad aligned on iPhones with Notch or Dynamic Island, but if you use Safari and you add it to home screen, the margins are fine.
 
Using the native App:
![iosapp](https://github.com/freescout-helpdesk/freescout/assets/93825819/d12c48a7-a8c8-4e6f-8aa9-502115148867)

Using Safari "Add to home screen" function:
![iosaddtohomescreen](https://github.com/freescout-helpdesk/freescout/assets/93825819/6e40d41a-4395-4601-a043-c01b0d292311)

**Comment by freescout-helpdesk** [comment] 2023-10-31 05:12
It looks like duplicate of https://github.com/freescout-helpdesk/freescout/issues/2693

**Closed** 2023-11-04 06:56 UTC
