### ISSUE TITLE
Dont work site.name/app-settings/emails

### ISSUE THREAD

**Issue by nart61** [freescout-helpdesk/freescout#2996] opened 2023-05-09 18:54 UTC
Hello

strstr(): Passing null to parameter #1 ($haystack) of type string is deprecated (View: /var/www/html/resources/views/settings/emails.blade.php) (View: /var/www/html/resources/views/settings/emails.blade.php) {"userId":2,"email":"mail@mail.com","exception":"[object] (ErrorException(code: 0): strstr(): Passing null to parameter #1 ($haystack) of type string is deprecated (View: /var/www/html/resources/views/settings/emails.blade.php) (View: /var/www/html/resources/views/settings/emails.blade.php) at /var/www/html/storage/framework/views/cb1b45fa9220d1465cc871cb9b6f6cf77a4cbb2e.php:49, ErrorException(code: 0): strstr(): Passing null to parameter #1 ($haystack) of type string is deprecated (View: /var/www/html/resources/views/settings/emails.blade.php) at /var/www/html/storage/framework/views/cb1b45fa9220d1465cc871cb9b6f6cf77a4cbb2e.php:49, ErrorException(code: 0): strstr(): Passing null to parameter #1 ($haystack) of type string is deprecated at /var/www/html/storage/framework/views/cb1b45fa9220d1465cc871cb9b6f6cf77a4cbb2e.php:49)

How to solve a problem?

**Comment by freescout-helpdesk** [comment] 2023-05-09 18:56
Duplicate of https://github.com/freescout-helpdesk/freescout/issues/2989

**Closed by freescout-helpdesk** 2023-05-09 18:56 UTC
