### ISSUE TITLE
Auto Workflow not running

### ISSUE THREAD

**Issue by TheMoodBoardz** [freescout-helpdesk/freescout#2786] opened 2023-03-01 10:43 UTC
Since the last update the Workflow module as stopped running auto jobs - we have one for staff onboarding so it adds a check list, emails customer & adds a tail but it's randomly stopped working

**Comment by endoflevelboss** [comment] 2023-03-02 09:18
Same issue here. Does not seem to be a general issue as only some workflows are affected and skipping executions does seem to follow a random pattern. The issue first appeared after updating to 1.8.60. I have been on 1.8.52 before.

Some observations:

Going to the workflow editor and re-saving the workflow with "apply to previous" selected will correctly execute, so the workflow definition clearly is functional. Workflow application is delayed after the manual trigger. It can take some seconds to apply after the editor window has been closed.

I'm having a larger number of workflows defined and processing time can be in the range of 1+ minute. In the task manager the workflow processing queue is active for that time.

Is there an exection time limitation in the worker queues? Or is there a connection with recent changes to avoid concurrent queue jobs that interfere when older jobs are running unexpectedly long?

Sorry for the fuzzy problem description, but I did not yet manage to better isolate the issue.

**Comment by freescout-helpdesk** [comment] 2023-03-02 18:28
> Is there an exection time limitation in the worker queues?

No.

@endoflevelboss Try to comment timeouts like this `// public $timeout = 120;` in all files in `/app/Jobs` and clear the cache. 

If it does not help try to downgrade your FreeScout step-by-step starting from [1.8.59](https://github.com/freescout-helpdesk/freescout/releases), then 1.8.58 and so on (using [manual update](https://github.com/freescout-helpdesk/freescout/wiki/Updating-FreeScout#method-5-update-manually) method) till Workflows will start working. This way we will know the release which is causing the issue.

**Comment by TheMoodBoardz** [comment] 2023-03-02 21:05
I have tried that just now & sent dummy tickets in but it has not started working but the module seems to be on the same version? 
My latest version is FreeScout 1.8.65 (Cloudron)

**Comment by freescout-helpdesk** [comment] 2023-03-03 05:22
@endoflevelboss @mendriph Are you also using Cloudron? Cloudron has it's own special way of running queue worker. So maybe this issue is related to it.

**Comment by endoflevelboss** [comment] 2023-03-03 09:10
Not using Cloudron. I'm running self hosted plain LAMP with cronjobs for the scheduled tasks.

**Comment by mendriph** [comment] 2023-03-03 11:29
I am not using Cloudron either. Freescout was installed by Softaculous (on CentOS + DirectAdmin). But I can say that I tried the Ubuntu script to install it and the result is the same.

There is a PHP execution timeout of 60 seconds, but I doubt it is related to the issue because the error message concerning the failed job appears seconds after the workflow is triggered. This rarely takes more than 5 seconds.

**Comment by freescout-helpdesk** [comment] 2023-03-03 16:45
We can't reproduce the issue. Debug it if you can. Also check logs in Manage > Logs > App Logs?

If someone can provide an access to your FreeScout to check it - feel free to email at support@freescout.net

**Comment by TheMoodBoardz** [comment] 2023-03-05 21:15
so after a bit of indepth checking it seems that auto jobs wont run if the email has "Reply To" set which since a recent change our emails contain this. Its odd that it wont run them though

**Comment by freescout-helpdesk** [comment] 2023-03-06 06:17
> so after a bit of indepth checking it seems that auto jobs wont run if the email has "Reply To" set which since a recent change our emails contain this. Its odd that it wont run them though

It works fine with "Reply To" on our end. There is nothing in Manage > Logs > App Logs?

**Comment by TheMoodBoardz** [comment] 2023-03-06 07:39
Nope - nothing in logs other than an error for an open source calendar module

**Comment by avenjamin** [comment] 2023-03-06 09:31
@TheMoodBoardz what was the recent change made to make `Reply-To` be included in your emails?

If it was something custom coded at your end are the headers formatted with the correct line endings?

I've had issues with wrong line endings before.

**Comment by TheMoodBoardz** [comment] 2023-03-06 11:02
@avenjamin we recently moved from Zapier (send mail not via the API) to our email and switching the customers manually however due to data protection and QOL improvements we moved over to MS PowerApps where we introduced Reply-To. Nothing in the FreeScout backend has been touched to introduce this lot of improvements

**Comment by endoflevelboss** [comment] 2023-03-07 08:49
I have been observing this for a couple of days now, and I do think the automatic workflows indeed will be triggered, but with significant delay only. I can't tell if this maybe is a random patern and something else will (re-)trigger workflow processing and runs previously missed workflows.

I also noticed that after manual workflow execution it may take some time before the workflow is applied after closing the editor screen. E.g. I can watch the counter decreasing slowly while the workflow closes communications. I have not noticed this delay earlier.

Is this a "scaling issue" and a problem that existed before just becomes visible as the database has reached a certain size and processing times become more significant?

**Comment by TheMoodBoardz** [comment] 2023-03-08 10:01
@endoflevelboss we have not seen the same result (it being delayed) - it just flat out wont work for us. we have changed how we handle these tickets in the short term though

**Comment by freescout-helpdesk** [comment] 2023-03-11 06:13
> problem that existed before just becomes visible as the database has reached a certain size and processing times become more significant?

It's possible. Also check your background processes, maybe there are some processes that got stuck after updating FreeScout like in this case: https://github.com/freescout-helpdesk/freescout/issues/2762#issuecomment-1447617205

**Comment by endoflevelboss** [comment] 2023-03-13 08:59
Just checked and did not find any stuck process. Checked all logs also and can't see anything conspicuous at all.

Automatic workflows continue to be executed randomly after a while. Could be minutes, could be hours.

Suggesting to make the event log for workflow execution more verbose by adding conditional check results on all messages processed. This could generally help debugging more complex workflow definitions.

**Comment by endoflevelboss** [comment] 2023-03-14 16:29
Just recognized the pattern in delayed workflow execution. It is not executed randomly as I assumed earlier, it it spot on by the full hour after the last message.

**Comment by endoflevelboss** [comment] 2023-03-15 07:49
Please find attached.
![1](https://user-images.githubusercontent.com/29640771/225241724-a84c5256-547f-4938-b696-e6561e2b637f.png)

**Comment by freescout-helpdesk** [comment] 2023-03-15 07:52
What's in the Subject condition? Does it contain any non-latin or special symbols?

**Comment by endoflevelboss** [comment] 2023-03-15 07:57
The subject is plain ASCII with no special characters.

**Comment by freescout-helpdesk** [comment] 2023-03-31 13:58
We'll close this as we could not reproduce mentioned issues. If someone will be able to determine the reason of those issues - feel free to share.

**Closed by freescout-helpdesk** 2023-03-31 13:58 UTC
