### ISSUE TITLE
Telegram Module only sending to channel for some users .. showing errors for others

### ISSUE THREAD

**Issue by satorisage** [freescout-helpdesk/freescout#2980] opened 2023-05-05 04:25 UTC
When I new ticket is submitted we get a single notification in telegram - this works perfectly.
When I reply to the ticket, telegram gets a message..
When someone else replies to it, we get this error:

May 4, 11:18:05pm | API error: Bad Request: can't parse entities: Unsupported start tag "xxx@xxx.com" at byte offset 338

**Comment by freescout-helpdesk** [comment] 2023-05-05 04:30
What is "xxx@xxx.com"? Support agent email?

**Comment by satorisage** [comment] 2023-05-05 04:39
Sorry! Yes, it's the service desk email.

**Comment by freescout-helpdesk** [comment] 2023-05-05 04:44
Where do you see this error? In which log?

**Comment by satorisage** [comment] 2023-05-05 04:45
Manage -> Logs -> Telegram

**Comment by freescout-helpdesk** [comment] 2023-05-05 04:51
Add the following code to the line 156 in /Modules/TelegramIntegration/TelegramIntegrationServiceProvider.php:
```
\Log::error('[Telegram Integration] Text: '.$text);
```
And send us the text starting with "[Telegram Integration]" from Manage > Logs > App Logs.

**Comment by satorisage** [comment] 2023-05-05 05:00
Well, presuming you are talking about the root Freescout directory
I have a php file that is "Modules/Telegram/Providers/TelegramServiceProvider.php"
The folder structure is not the same as you suggested... as there is no "TelegramIntegration" folder.
This is the module that sends tickets from Freescount into the Telegram channel and not that other one which creates tickets from the Telegram channel.

**Comment by freescout-helpdesk** [comment] 2023-05-05 05:03
You are talking about https://freescout.net/module/telegram/. Write a step-by-step instruction on how to reproduce the issue.

**Comment by satorisage** [comment] 2023-05-05 05:06
Yes that is the module. Okay I will test it further and write back once my co-worker who was having the issue returns. Thanks!

**Comment by satorisage** [comment] 2023-05-05 16:08
It seems right now, the error only happens from outlook app on android.

If I create a ticket and my co worker tries to reply from outlook on
android, if gives that error any time he tries to reply. If I reply from my
outlook app it works fine. I am on iOS. His reply shows up correctly in in
freescout and in my email notification, but we do not get the message in
the telegram channel and it gives that error in the logs. The “byte offset”
does change each time also.

**Comment by freescout-helpdesk** [comment] 2023-05-05 16:50
> my co worker tries to reply from outlook on android

Do you mean your co-worker replies to an email notification from Outlook on Android?

Please share the body of the email sent by your co-worker - you can find it in "Show Original" window in message's dropdown menu in FreeScout.

**Comment by satorisage** [comment] 2023-05-05 19:27
It seems the issue is not exclusive to android.

We just had a customer write us, I replied to the email notification from
outlook on iOS, and we got this same error.

**Comment by freescout-helpdesk** [comment] 2023-05-06 04:55
> Please share the body of the email sent by your co-worker - you can find it in "Show Original" window in message's dropdown menu in FreeScout.

We need this.

Also add the following code to the line 277 in /Modules/Telegram/TelegramServiceProvider.php:
```
\Log::error('[Telegram] Message: '.$message);
```

And send us the text starting with "[Telegram]" from Manage > Logs > App Logs.

**Comment by satorisage** [comment] 2023-05-06 18:53
`Please go inside. If it's still windy,  close the door
<div><br></div>
<div id="ms-outlook-mobile-signature" dir="auto">
<div dir="auto">Sent from my chat gpt neural implant.</div>
<div dir="auto">Brought to you by the borg queen.</div>
<div dir="auto">Resistance is futile. You will be assimilated. </div>
</div>
<hr style="display:inline-block;width:98%" tabindex="-1">
<div id="divRplyFwdMsg" dir="ltr">
<font face="Calibri, sans-serif" style="font-size:11pt" color="#000000"><b>From:</b> Peoria IT Service & Support <service@peoriait.com><br><b>Sent:</b> Friday, May 5, 2023 10:48:22 AM<br><b>To:</b> Stephen Halsey <stephen@peoriait.com><br><b>Subject:</b> [#2850] Its too windy</font>
<div> </div>
</div>
<style>

</style>
<div style="background-color:#f8f9f9; margin:0">
<table bgcolor="#f8f9f9" cellspacing="0" border="0" cellpadding="0" width="100%"><tbody>
<tr>
<td>
<table class="x_content" width="100%" border="0" cellspacing="0" cellpadding="0"><tbody>
<tr>
<td height="45" valign="bottom">
<p align="center" style="font-family:Arial,'Helvetica Neue',Helvetica,Tahoma,sans-serif; font-size:12px; color:#B5B9BD; line-height:16px; margin:0"`

Email body ^

I added the code.. will the text you request appear in the log when the error happens again or at another time?

**Comment by satorisage** [comment] 2023-05-06 18:57
I had him reply again and nothing new in the logs after adding that line on row 277.. just the same error:


May 6, 01:56:04pm | API error: Bad Request: can't parse entities: Unsupported start tag "service@peoriait.com" at byte offset 278
-- | --

**Comment by freescout-helpdesk** [comment] 2023-05-06 21:59
After foreach before the try block. Also clear the cache in Manage > System > Tools.

**Comment by freescout-helpdesk** [comment] 2023-05-06 22:01
It looks like the error occurs because of such text `<xxx@xxx.com>` in the body.

**Comment by satorisage** [comment] 2023-05-06 22:20
> It looks like the error occurs because of such text `<xxx@xxx.com>` in the body.

Is this because the email address there is within a <font> tag?

From what I can gather Outlook on mobile is replying with the HTML from notification and it is included there.

I just cleared cache and asked him to try again... just waiting for it now.

**Comment by satorisage** [comment] 2023-05-06 22:46
Each time we try and send from outlook on mobile the App Logs Errors are this:

<html>
<body>


error | production | 2023-05-06 17:44:04 | [Telegram] Message: Stephen Halsey <b>replied</b> <a href="https://freescout.peoriait.com/conversation/2850?folder_id=3">#2850</a>
-- | -- | -- | --
error | production | 2023-05-06 17:34:06 | [Telegram] Message: Stephen Redding <b>replied</b> <a href="https://freescout.peoriait.com/conversation/2850?folder_id=3">#2850</a>


</body>
</html>

**Comment by satorisage** [comment] 2023-05-06 23:03
When I click the reply button in Outlook (ios or android), it automatically fills in that text with the From and To information right below the signature. We actually don't like that being there in the conversation between the customers.. but I cannot find a way to turn it off in the Outlook app. When I reply in Gmail it doesn't do that, neither does it do it on Outlook Desktop app.

**Comment by freescout-helpdesk** [comment] 2023-05-07 06:13
Fixed in Telegram Notifications Module v1.0.11

**Comment by satorisage** [comment] 2023-05-07 06:44
perfect! tested and working... how can i buy yall a round of coffee???!

**Comment by freescout-helpdesk** [comment] 2023-05-07 06:46
Starring this repo would be enough.

**Closed by freescout-helpdesk** 2023-05-07 06:46 UTC

**Comment by satorisage** [comment] 2023-05-07 06:49
Done - and thank you again so much! yall rock!!
