### ISSUE TITLE
Conversations are going in Draft and staying there

### ISSUE THREAD

**Issue by amityweb** [freescout-helpdesk/freescout#234] opened 2019-01-16 09:55 UTC
Freescount seems to be working well for us except one issue at the moment...

Our Drafts folder has loads of emails in there.

Some do show a Draft status at the top with the option to Edit or Discard. But we would have sent them, they would not be Drafts. We cant tell if they are sent now, we will have to ask the customer if they got it. 

Some do not have any Draft/Unsent message and all look OK with no reason to be in Drafts. 

One of them in Drafts was a customer actually emailed us, and when I clicked the link in the email it opened up their message in an editor as if I was writing it, with my support email as the To email and the customer not listed. So there was no reply option.. I had to send it, then when it came in, change the customer so I can then reply. I dont know if this is a related issue or different. I think her email to me may have been a reply to an email I created in Freescout so the system sent it to them. So maybe something to do with replying to an email I created to the customer. 

So there is definitely an issue with Drafts.

**Comment by freescout-helpdesk** [comment] 2019-04-29 10:27
Do you still experience this issue with new conversations?

Few issues with drafts were fixed in 1.1.1, 1.1.2 and 1.1.4

**Comment by jclimac** [comment] 2019-06-06 17:05
Hello there!

I'm also experiencing this issue as well. I'm on version 1.1.7

When I reply to a conversation it is correctly sent to the customer, but the conversation is "duplicated", I have one on Mine folder and one, the same one, on Draft folder.

Even when I mark the conversation as Closed it remains on Draft folder, the "duplicated" version is correctly moved from Mine folder to Closed folder.

**Comment by freescout-helpdesk** [comment] 2019-06-07 05:22
@jclimac Are you using the lastest version of the FreeScout?

**Comment by jclimac** [comment] 2019-06-07 07:36
@freescout-helpdesk no, I'm using version 1.1.7, I did not update to the last version because I had to do the modification referenced here #253 in order to be able to fetch emails on my Exchange server.

I will update and report here.

**Comment by jclimac** [comment] 2019-06-07 08:23
@freescout-helpdesk Ok, just updated and the behavior is the same.

BUT, I have done some further tests and discovered something a lithe bit odd.

If I receive a conversation, open it up, answer it in just some seconds, just like an "Ok, done" and send the draft is created. If I take more time to answer the conversation, like 30 seconds or more, there is no draft saved.

Doing a even more further investigation I think the problem is when I hit send BEFORE the automatic draft get saved, a grey check mark on top right of the reply text box.

If I hit send with that check green there is no draft on Draft folder.

**Closed** 2019-06-27 08:58 UTC
