### ISSUE TITLE
Attachment with unknown characters are not showing up

### ISSUE THREAD

**Issue by eisennheart** [freescout-helpdesk/freescout#2123] opened 2022-07-28 07:49 UTC
Email attachments(with unknown character/s) are not showing up on the FreeScout.  

<img width="724" alt="image" src="https://user-images.githubusercontent.com/92557519/181447582-62340e86-0274-43bb-bda2-7c900d74dee7.png">

Some part within the name of the attachment cannot be encoded properly.  

<img width="670" alt="image" src="https://user-images.githubusercontent.com/92557519/181447895-43a9a758-63d7-4fac-90d0-af7e9e9f54be.png">

Tried to load the email file on a different client like Thunderbird, we can see there's an unknown character(Ü) on the name of the file.

<img width="628" alt="image" src="https://user-images.githubusercontent.com/92557519/181448868-72a938c5-05a4-4076-9b09-97ec75e8d06e.png">

FreeScout 1.8.11
PHP 7.3.31
Nginx 1.20.2
Locale en_US.UTF-8

**Comment by freescout-helpdesk** [comment] 2022-07-28 07:57
Could you please attach here an example of such file.

**Comment by eisennheart** [comment] 2022-07-28 09:21
I can't replicate the attachment, literally getting the filename from copy and paste.  I got some of the reported attachments but they have sensitive information.  Can I upload the email file or the attachment somewhere privately?

**Comment by freescout-helpdesk** [comment] 2022-07-28 09:44
You can send it to support@freescout.net

**Comment by eisennheart** [comment] 2022-07-28 11:55
Sent the email file

**Comment by freescout-helpdesk** [comment] 2022-07-29 13:22
The attachment you've sent is visible and downloadable in FreeScout:

![2022-07-29_16-21-40](https://user-images.githubusercontent.com/40499291/181769496-7e1bc962-b589-4a67-9732-820e42264c1d.png)

**Comment by eisennheart** [comment] 2022-07-31 02:23
What I have sent you is actually the email file from our IMAP server.  The
issue is, FreeScout can't load the attachment from that email when
fetched.  Look for the lines

Content-Type: application/pdf;

name*=UTF-8''FLYHID-01%20-%20Flydream%20OU%CC%88%20-%20Hidden%20Gem%20-%2040185.pdf
Content-Transfer-Encoding: base64
Content-Disposition: attachment;

filename*=UTF-8''FLYHID-01%20-%20Flydream%20OU%CC%88%20-%20Hidden%20Gem%20-%2040185.pdf

Somewhere on the filename of the attachment can't be properly encoded by
FreeScout.  But if I open the file using Thunderbird, the attachment can be
seen below and can be downloaded.

[image: image.png]

**Comment by freescout-helpdesk** [comment] 2022-07-31 04:45
Are you using modern Microsoft Office authentication or regular IMAP authentication to fetch emails?

**Comment by eisennheart** [comment] 2022-08-01 05:56
We are using dovecot with regular IMAP authentication

**Comment by freescout-helpdesk** [comment] 2022-08-01 06:09
We can't figure out how to reproduce the issue. If you'll manage to fix it - feel free to submit a pull request.

**Comment by eisennheart** [comment] 2022-08-01 16:29
If you have a dovecot IMAP server, you can just drop the email file in the
"new" directory.  Then once the email was fetched by FreeScout, the file
will be moved to the "cur" directory.  But the important thing is, when
FreeScout loads the email, the expected attached file should also be loaded
as should be seen from the Thunderbird.

I do not have a background for PHP development so I will not be able to fix
it.  Since this is related to character encoding, aside from following the
Installation Instructions and FAQ, is there something else that needs to be
done ensuring all settings are UTF8?

**Comment by ilyakonovalenko** [comment] 2022-08-01 16:58
> is there something else that needs to be done ensuring all settings are UTF8?

Your database server should support utf8mb4_unicode_ci encoding. 

There can also be FreeScout code issue with iconv conversion or something, someone will need to check. I will try to figure out if it is related to FreeScout.

**Comment by eisennheart** [comment] 2022-08-02 06:39
This is what we have on the database

[image: image.png]

**Comment by freescout-helpdesk** [comment] 2022-08-02 06:44
The image is not visible.

**Comment by eisennheart** [comment] 2022-08-04 00:32
As sent to the support email

<img width="1305" alt="image" src="https://user-images.githubusercontent.com/92557519/182737916-3c4f58f6-ed2d-47d1-afb8-26cee8e32008.png">

**Comment by ilyakonovalenko** [comment] 2022-08-04 06:44
Can you please send original file name which is not saved? I will try to create such file and test it out.

**Comment by eisennheart** [comment] 2022-08-04 07:56
I have sent the email file to support@freescout.net from previous conversations since it contains sensitive information.  Do you want me to send it to support@freescout.net again or to something else privately?

**Comment by freescout-helpdesk** [comment] 2022-08-04 08:01
You can post just the filename here.

**Comment by ilyakonovalenko** [comment] 2022-08-04 08:02
I don't need the file, I need to know original file name.

**Comment by eisennheart** [comment] 2022-08-04 08:22
Filename is 

FLYHID-01 - Flydream OÜ - Hidden Gem - 40185.pdf

**Comment by eisennheart** [comment] 2022-08-05 02:54
We tried to replicate.  Downloaded the attachment using Thunderbird and sent it to FreeScout.  Viewing the email file, noticed the differences how the filename has been generated.

Not working(originally came from our third-party):

filename*=UTF-8''FLYHID-01%20-%20Flydream%20OU%CC%88%20-%20Hidden%20Gem%20-%2040185.pdf

Working:

filename="=?utf-8?Q?FLYHID-01_-_Flydream_O=C3=9C_-_Hidden_Gem_-_40185.pdf?="

**Comment by freescout-helpdesk** [comment] 2022-08-17 11:42
We've sent a file with such name and it arrived to FreeScout. We'll close this issue as we can't reproduce it.

**Closed by freescout-helpdesk** 2022-08-17 11:42 UTC
Labels: help wanted

**Comment by pv8888888** [comment] 2025-04-02 11:25
another example is that we received a mail with 3 attachments with file names similar to this: CamScanner_٢٨‏-٠٣‏-٢٠٢٥_١١.٤٠.jpg

![Image](https://github.com/user-attachments/assets/cc5b6c27-6bfd-4751-a51f-115e0dea0617)... 

It has special characters in the names, and it only stored a record for one attachment in the attachments table, without storing the file. 

Names should be sanitized!

**Comment by freescout-help** [comment] 2025-04-03 05:51
Fixed in the `master` branch and will be published in the next release.
https://github.com/freescout-help-desk/freescout/commit/0e83d360b5b0cb0cb82177cdb936615f6569da40

**Comment by pv8888888** [comment] 2025-04-03 06:48
Thats great !!!!

**Comment by stsimb** [comment] 2025-04-03 11:03
The RLM character (Right-to-Left Mark) is considered a formatting character and RLM, with a Unicode code point of U+200F, is categorized under: General Category: Format (denoted as Cf), which stands for other format characters.

Thus, it will not be matched by \p{C} since \p{Cf} (format characters) is a different category than \p{C} (control characters). If you need to match format characters like RLM, you would use \p{Cf} instead.

@freescout-help Could you additionally remove format characters from the filenames please ?

Thanks!

**Comment by freescout-help** [comment] 2025-04-03 11:26
> Could you additionally remove format characters from the filenames please ?

Will you be able to submit a pull request for this or post here the code?

**Comment by stsimb** [comment] 2025-04-03 13:24
like in https://github.com/freescout-help-desk/freescout/commit/0e83d360b5b0cb0cb82177cdb936615f6569da40
line 1821

        $file_name = preg_replace("#\p{Cf}+#u", '', $file_name);
