### ISSUE TITLE
Activating Knowledge Base Module duplicates port in links

### ISSUE THREAD

**Issue by kevinorin** [freescout-helpdesk/freescout#2736] opened 2023-02-16 22:02 UTC
First time using FreeScout. After prepping the local OSX environment it was installed flawlessly on PHP 7.2.8. All I've done so far is install the mailbox SMTP (the test email worked fine).

Immediately after purchasing and installing the Knowledge Base Module all navigation links are broken. See loom: https://www.loom.com/share/0b5c50c1166a41ac8947390ccb69bc41

I ran `php artisan freescout:clear-cache ` which didn't solve the issue. All admin links are inaccessible.

Please advise...

**Comment by kevinorin** [comment] 2023-02-17 00:34
**Update:** I installed another installation of FreeScout to get the admin paths/urls and the application appears to be working but activating the Knowledge Base breaks the menu navigation.

**Loom** (fb-support:8888 is original installation with Knowledge Base, fb-fs:8888 is new installation I'm using to get correct paths/urls) : https://www.loom.com/share/30d9169fc1e0406ca89a99611b84749d

**Comment by freescout-helpdesk** [comment] 2023-02-18 11:12
See https://github.com/freescout-helpdesk/freescout/wiki/FreeScout-Modules#-application-or-module-is-not-working-after-installing-a-module

**Comment by kevinorin** [comment] 2023-02-18 14:56
> See https://github.com/freescout-helpdesk/freescout/wiki/FreeScout-Modules#-application-or-module-is-not-working-after-installing-a-module

I've gone through all of that, which suggestion applies to my issue? This is a VERY specific issue and I can't believe it's never come up considering this is a vanilla install. All I've done is install FreeScout, Setup a Mailbox + Activate the Knowledge Base app.

I signed up for the FS KB demo to get the paths, and if I input the path URLs manually on my local they work...it's just navigating within FreeScout that's breaking when I enable the module.
SEE: https://www.loom.com/share/76ab11f2c9694bd9a4c590dc3b0a7790

**Comment by kevinorin** [comment] 2023-02-18 15:00
Generally, when you hover on a link, it shows you the path in bottom left browser status. Once I activate the module, none of the links even non-KB links show up in status. Clicking any link takes me to "about:blank#blocked"

![Screen Shot 2023-02-18 at 9 58 19 AM](https://user-images.githubusercontent.com/1056402/219872725-175200ad-a676-4290-920d-86e92f8a444f.png)
![Screen Shot 2023-02-18 at 9 59 00 AM](https://user-images.githubusercontent.com/1056402/219872730-d795c609-9e66-494c-9a35-b5adaa422bfa.png)

**Comment by freescout-helpdesk** [comment] 2023-02-18 18:35
What's your APP_URL in .env file?

**Comment by kevinorin** [comment] 2023-02-18 18:41
> What's your APP_URL in .env file?
> 
> Also try to open HTML code of the page and find what's in the `<a href="...">`

APP_URL=http://fb-fs:8888

I've checked that, the weird thing is the URLs are fine in the html. I'm completely stumpped: https://www.loom.com/share/d3a3db157c1b4ac0a0d51904484320cb

**Comment by freescout-helpdesk** [comment] 2023-02-19 04:51
Maybe there is some extension in your browser blocking those links. Also check messages in the browser console.

**Comment by Fraele** [comment] 2023-03-02 09:55
PHP 8.0.28 apache 2.4 on Ubuntu.
Just installed about 20 original modules, I have the same problem with just "Extended Attachments", when active navigation links are broken. 
All other modules are working.
Tried the suggestions without success.

**Comment by totake0224** [comment] 2023-06-07 05:27
version 1.8.80 ( using docker tiredofit/freescout)
I am having this problem too.
I could inactivate Knowledge Base module by accessing /modules/list .
and freescout navigation is recovered.
I check source of page.
link url become wrong after knowledge base activated.
my SITE_URL is  https://192.168.1.4:4001
before activate knowledge base                                      after activate knowledge base
https://192.168.1.4:4001/global-mailbox/1    ->         https://192.168.1.4:4001:4001/global-mailbox/1

**Comment by freescout-helpdesk** [comment] 2023-06-07 06:04
Are you all using Docker?

**Comment by totake0224** [comment] 2023-06-07 07:15
I use docker and I just start it from tiredofit/freescout.
I set only 4 parameter except DB parameter.
`SITE_URL https://192.168.1.4:4001`
`APP_NEW_FETCHING_LIBRARY true`
`APP_FORCE_HTTPS true`
`ENABLE_SSL_PROXY true`
the instance is for private network. no one could access it from outside.

In addition to,
I use reverse proxy like,
192.168.1.4:4001  -> nginx(server) ->   nginx(docker)

**Comment by freescout-helpdesk** [comment] 2023-06-07 07:58
Can you add the following code to the second line of https://github.com/freescout-helpdesk/freescout/blob/dist/public/index.php, open some FreeScout page and send us the output:
```
echo "<pre>";
print_r($_SERVER);
exit();

**Comment by totake0224** [comment] 2023-06-07 08:03
Array
(
    [TEMP] => /tmp
    [TMPDIR] => /tmp
    [TMP] => /tmp
    [PATH] => /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    [USER] => nginx
    [HOME] => /var/cache/nginx
    [HTTP_COOKIE] => _CrPoSt=cHJvdG9jb2w9aHR0cHM6OyBwb3J0PTUxMDE7IHBhdGhuYW1lPS87; _SSID=5gtBGUN6TsuzOPmRt7vXXjIHKUhO7CvF3sab4vXr7CI; stay_login=0; did=-ik4B8BY10ehukTVzyIXhdHyQvoSwt4zA9hu95oB3FM9ZrZFDJxDVjlNd36EDYeLcVOBHshBqxTnIvyTkhMUqg; laravel_session=eyJpdiI6IlhKaGV3MzdOZVpPYitRblQ2WGN5Umc9PSIsInZhbHVlIjoiZHo4XC9ueUVud0ptMGpPUHl2RnJuaHE5UWV5dVY1WWMxdUJuMzBQaWFWVnlic0FCc3hIR0tvZWpITk45WWg3cGVZampaaTJsa2lUTjZHZ0xcL3BrQ2dMdz09IiwibWFjIjoiMGQ5YmIxNTUxOTE0NzkwMTM0YTI2ZjdkMTcxZDQzMWMyOGRiZTBkZDRkMmZhMWVjZGYzNzMxZTAzOWQ3MjRiMiJ9; XSRF-TOKEN=eyJpdiI6IjJScGpMQUV5WGdkdFlHeDRyRXo3S2c9PSIsInZhbHVlIjoiVDJQUm1QVklmZmRYdk1IZ2hKU3drS2s1cnZyOGJpekFYVjhsWmJodFlUZzlxQnJUQ2dIR1k5cW9Jd3N1b3JNQWpPZzNVNEt1eSt5MUd1aE1TcjZJT1E9PSIsIm1hYyI6Ijc5MmY1NDU0YjhhOGMyNGVmNmFkNDhjNzMzN2FmZjZmZjcwM2NkMWZmNTJjNzMzMmI2ZWYwNzBjYTJjNWNmZGUifQ%3D%3D; io=-QRexVxsdS4kGV9dAAAG; id=n2mO7sjOe2T9eduVx_eoGye7z5C2oXrYAA4TK8Dhjq4Ke63GdO4iW5mqK-Hc4ybgQqVMrif_pf1VyZJwlkSxJc
    [HTTP_SEC_FETCH_USER] => ?1
    [HTTP_SEC_FETCH_SITE] => none
    [HTTP_SEC_FETCH_MODE] => navigate
    [HTTP_SEC_FETCH_DEST] => document
    [HTTP_UPGRADE_INSECURE_REQUESTS] => 1
    [HTTP_ACCEPT_ENCODING] => gzip, deflate, br
    [HTTP_ACCEPT_LANGUAGE] => ja,en-US;q=0.7,en;q=0.3
    [HTTP_ACCEPT] => text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8
    [HTTP_USER_AGENT] => Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/113.0
    [HTTP_CONNECTION] => close
    [HTTP_X_FORWARDED_PROTO] => https
    [HTTP_X_FORWARDED_FOR] => 192.168.1.99
    [HTTP_X_REAL_IP] => 192.168.1.99
    [HTTP_HOST] => 192.168.1.4:4001
    [STAGE] => DEVELOP
    [REDIRECT_STATUS] => 200
    [SERVER_NAME] => 
    [SERVER_PORT] => 80
    [SERVER_ADDR] => 172.17.0.2
    [REMOTE_PORT] => 
    [REMOTE_ADDR] => 192.168.1.99
    [SERVER_SOFTWARE] => nginx/1.25.0
    [GATEWAY_INTERFACE] => CGI/1.1
    [HTTPS] => off
    [REQUEST_SCHEME] => http
    [SERVER_PROTOCOL] => HTTP/1.1
    [DOCUMENT_ROOT] => /www/html/public
    [DOCUMENT_URI] => /index.php
    [REQUEST_URI] => /
    [SCRIPT_NAME] => /index.php
    [CONTENT_LENGTH] => 
    [CONTENT_TYPE] => 
    [REQUEST_METHOD] => GET
    [QUERY_STRING] => 
    [SCRIPT_FILENAME] => /www/html/public/index.php
    [FCGI_ROLE] => RESPONDER
    [PHP_SELF] => /index.php
    [REQUEST_TIME_FLOAT] => 1686124963.2528
    [REQUEST_TIME] => 1686124963
)

**Comment by totake0224** [comment] 2023-06-07 08:49
Thank you.

**Comment by totake0224** [comment] 2023-06-07 10:13
> Fixed in Knowledge Base Module v1.0.48

it's not fixed completely.
I check source of knowledge base.
still exist duplicated port url.

`<link href="https://192.168.1.4:4001:4001//css/builds/907c094646eda3281b44bb458f4459ec16861176695.css" rel="stylesheet">
`
`<script src="https://192.168.1.4:4001:4001//js/builds/67b1466e9ab9377ffaf113906fbc65c813488906803.js"></script>
`

**Comment by freescout-helpdesk** [comment] 2023-06-07 11:38
> <link href="https://192.168.1.4:4001:4001//css/builds/907c094646eda3281b44bb458f4459ec16861176695.css" rel="stylesheet"> 
> <script src="https://192.168.1.4:4001:4001//js/builds/67b1466e9ab9377ffaf113906fbc65c813488906803.js"></script> 

Does the issue persist with deactivated Knowledge Base Module?

**Comment by totake0224** [comment] 2023-06-08 23:44
I’ｍ sorry for lack of explanation.
`<link href="https://192.168.1.4:4001:4001//css/builds/907c094646eda3281b44bb458f4459ec16861176695.css" rel="stylesheet"> `
`<script src="https://192.168.1.4:4001:4001//js/builds/67b1466e9ab9377ffaf113906fbc65c813488906803.js"></script> `
this is not top page of freescout.
this is source of knowlege base page. so my knowlege base page looks very simple. because of lack of css.

**Comment by freescout-helpdesk** [comment] 2023-06-13 07:58
> I’ｍ sorry for lack of explanation. `<link href="https://192.168.1.4:4001:4001//css/builds/907c094646eda3281b44bb458f4459ec16861176695.css" rel="stylesheet"> ` `<script src="https://192.168.1.4:4001:4001//js/builds/67b1466e9ab9377ffaf113906fbc65c813488906803.js"></script> ` this is not top page of freescout. this is source of knowlege base page. so my knowlege base page looks very simple. because of lack of css.

We can't reproduce this issue.

**Comment by freescout-helpdesk** [comment] 2023-06-13 08:07
Are you using a Custom Domain option? If so what's is the value of Custom Domain option?

**Comment by totake0224** [comment] 2023-06-13 08:38
I didn't hava Custom Domain option(Is it one of modules?)
I'm using CRM,GlobalMailbox,KnowlegeBase,SPAMfilter,Tags,Teams and Workflows.

**Comment by freescout-helpdesk** [comment] 2023-06-13 08:42
Ok. It is an option in Knowledge Base Module settings.
Anyway we could not reproduce the issue with CSS and JS paths in Knowledge Base pages. So it should be investigated on your server.

**Comment by totake0224** [comment] 2023-06-13 08:49
I will try to check souce of Knowlege Base.

**Comment by totake0224** [comment] 2023-06-13 08:57
By the way, could you tell me where Custom Domain option parameter stored.
I set some value to it. after that I could not open entire Freescout at all.

**Comment by freescout-helpdesk** [comment] 2023-06-13 17:35
> By the way, could you tell me where Custom Domain option parameter stored.

In DB in `meta` field of `mailboxes` table.

**Comment by totake0224** [comment] 2023-06-13 23:46
Thank you.
I could recover my freescout.

**Comment by freescout-helpdesk** [comment] 2023-06-14 05:51
All issues have been fixed in Knowledge Base Module v1.0.49

**Closed** 2023-06-15 05:34 UTC
