### ISSUE TITLE
Not picking up emails

### ISSUE THREAD

**Issue by lovetoast** [freescout-helpdesk/freescout#692] opened 2020-08-10 16:30 UTC
Hi, 

This looks great but doesn't appear to be working for me. I have connected successfully via POP3 to a mailbox, but new emails aren't being picked up, replies aren't being picked, essentially, nothing is being picked up as you may have gathered.

The fetch email cron is running but not queued jobs. There are no queued jobs in fact? 

Wondering if anyone would be kind enough to assist?

**Comment by dsukhin** [comment] 2020-08-11 03:51
go to **Manage->System->Tools** and run an import from there. What does the log say? Perhaps all your messages are already unread? The tool will let you ignore that option.

**Comment by lovetoast** [comment] 2020-08-11 06:07
Morning! There are read and unread messages, neither are being picked up. When I click fetch in tools, that doesn't do anything either, just says:

```
[2020-08-11 06:05:53] Fetching ALL emails for the last 3 days.
[2020-08-11 06:05:53] Mailbox: Support
[2020-08-11 06:05:53] Fetching finished
```

**Comment by dsukhin** [comment] 2020-08-11 13:40
Did you set your folder names under Mailbox settings? Try adding those explicitly in the incoming connection settings.
Since this works well for others, I imagine this is a settings error rather than a code issue. I am happy to continue to troubleshoot with you, but recommend the issue be closed as it's not a bug.

**Comment by lovetoast** [comment] 2020-08-11 13:46
Hi Dsukhin, thanks for your help, I understand, but I feel it may be a bug.

So if I set as Inbox - and click fetch, it marks the emails as read but doesn't do anything

If I set the folder to inbox2, and put unread emails in there, it does nothing at all.

**Comment by dsukhin** [comment] 2020-08-11 13:53
same question as above - please provide the log of the import where you saw the messages being marked as read by marking some messages as unread using your mail client and trying again. I suspect you will see a message which says "message already imported" but please provide the log.

Do you have access to to the backend database (and knowledge how to check there) to see if the messages are in the `conversations `and `threads `tables and perhaps you need to change some settings in the UI?

**Comment by lovetoast** [comment] 2020-08-11 14:41
Hi @dsukhin 

So I was trying again, my IMAP on 993 wasn't working so I did POP3, and it wasn't happy.

I then did IMAP on the insecure port 143 and that is fine, so it turns out the issue is with the POP3 implementation?

The cron is working so that's great, but:


Last run: ? Last successful run: ? Try to clear cache to force command to start.
--


I've got this next to the 

queue:work cron on the system page? Should there be anything against this, because the fetch email has the last time, I attempted to clear the cache a few times, but it wasn't happy with that. The jobs are listed as 0 and 0 below this
--

Again, thanks for your help

**Comment by freescout-helpdesk** [comment] 2020-08-27 12:21
Closing for no activity.

**Closed by freescout-helpdesk** 2020-08-27 12:21 UTC

**Comment by gdandersson** [comment] 2022-02-10 08:19
Same here with POP3
[2022-02-10 09:16:23] Fetching ALL emails for the last 3 days.
[2022-02-10 09:16:23] Mailbox: x
[2022-02-10 09:16:23] Mailbox: x2
[2022-02-10 09:16:23] Fetching finished

Nothing fetched even though there are emails there.

Fresh installation with two POP3 accounts.

<img width="660" alt="Screenshot 2022-02-10 at 09 18 48" src="https://user-images.githubusercontent.com/52959348/153366150-3c802aaf-277e-4f1a-bb75-ff261c58b3fb.png">
