### ISSUE TITLE
Email fetching terminates after exactly 60 seconds when running

### ISSUE THREAD

**Issue by grrinch** [freescout-helpdesk/freescout#3844] opened 2024-03-02 23:33 UTC
Just stumbled across a problem with fetching emails.

What happens is, after exactly 60 seconds, the fetching command gets terminated with the following message in the fetching log:

`Terminated`
![image](https://github.com/freescout-helpdesk/freescout/assets/5729796/e6f41118-5a6f-48dc-8997-4d1c736dc37f)

I am using crontab with the standard command from the documentation:
```
* * * * * php /var/www/html/artisan schedule:run >> /dev/null 2>&1
```

Of course, first what I checked were the `memory_limit` and `execution_time` values in php.ini.

What's really weird is that when I run this command as the correct user, etc:
```
php /path/artisan freescout:fetch-emails
```
it finishes everything fine. The problem is only when it's running with cron and 100% terminates exactly after 60 seconds.

Not sure when it started occurring exactly because the users just brought up to my attention that some mailboxes are not receiving the emails.

If it helps, I updated Freescout to the latest version approximately a week ago.

Could this be something related to this issue: https://github.com/freescout-helpdesk/freescout/issues/3417

Anywhere else, would you suggest for me to have a look to fix it?

PHP version: 7.4.3-4ubuntu2.20 (cli) (built: Feb 21 2024 13:54:34) ( NTS )
FreeScout version: 1.8.122 
Database: MySQL 8.0.36-0ubuntu0.20.04.1 (Ubuntu)
Are you using CloudFlare: Yes

**Comment by freescout-helpdesk** [comment] 2024-03-08 06:31
We've never tried to run cron jobs via supervisor. If you'll find out the reason, please let us know.

**Comment by grrinch** [comment] 2024-03-11 07:06
Hi, yes, sorry, it's not run with supervisor anymore. I did, initially, but then switched over to cron to see if it helps and if you read the issue, it is referring to cron only.

**Comment by freescout-helpdesk** [comment] 2024-03-11 07:10
Check Manage > Logs > App Logs
Apparently something happens during the fetching and the processes dies due to some error or killed by operating system.

**Comment by grrinch** [comment] 2024-03-11 09:07
Checked all  the logs and there's nothing that would indicate that it's error or system. 

The processes restart end to make space to execute them again, this is why I strongly think it's being killed by Freescout similarly to this issue:
https://github.com/freescout-helpdesk/freescout/issues/3417

I only commented out this line in `app/Console/Kernel.php` and it started working, so it's definitely the code issue:
https://github.com/freescout-helpdesk/freescout/blob/2d74977ed3b17196b363945ad7b4c427d5144461/app/Console/Kernel.php#L124

**Comment by freescout-helpdesk** [comment] 2024-03-11 09:12
Is everything OK in `php artisan freescout:check-requirements`?

**Comment by grrinch** [comment] 2024-03-11 09:13
All good:
![image](https://github.com/freescout-helpdesk/freescout/assets/5729796/bf686480-2010-4816-910e-a275d608aa0e)

I updated the above comment for clarity.

**Comment by freescout-helpdesk** [comment] 2024-03-11 09:17
Check if `$mutext_name` has some value here: https://github.com/freescout-helpdesk/freescout/blob/2d74977ed3b17196b363945ad7b4c427d5144461/app/Console/Kernel.php#L113

And you'll need to figure out why `\Cache::get($mutex_name)` is empty. Maybe something is clearing cache on your FreeScout instance or by some reason FreeScout can not save that variable into the cache.

https://github.com/freescout-helpdesk/freescout/wiki/Debugging

**Comment by grrinch** [comment] 2024-03-11 10:37
Where exactly are you saving it to the cache? I couldn't find it anywhere in the code...

**Comment by freescout-helpdesk** [comment] 2024-03-11 10:56
`$schedule->command($fetch_command_name)` automatically creates a mutex in the cache.
https://github.com/freescout-helpdesk/freescout/blob/2d74977ed3b17196b363945ad7b4c427d5144461/app/Console/Kernel.php#L140C26-L140C65

**Comment by grrinch** [comment] 2024-03-11 12:26
Hmm, OK, I did some debugging - trying to save all the information around the `shell_exec('kill ', ....)` lines.

Here's the log when it runs while the first fetching (Started 1 minute earlier, set to every 5 minutes) is still running:

```
[2024-03-11 13:11:01] production.ERROR: DEBUG (Line 105 $fetch_command_name - checking the identifier ): s:32:"139ebc338793389ff5a37be0e259aff7";
[2024-03-11 13:11:01] production.ERROR: -----DEBUGGING AROUND THE FIRST `KILL PID` COMMAND-----
[2024-03-11 13:11:01] production.ERROR: DEBUG (Inside if ($this->isScheduleRun() && function_exists('shell_exec'))
[2024-03-11 13:11:01] production.ERROR: DEBUG (\Helper::getRunningProcesses($fetch_command_identifier)) - $fetch_command_pids value is: a:1:{i:0;s:5:"21352";}
[2024-03-11 13:11:01] production.ERROR: DEBUG ($mutex_name): s:59:"framework/schedule-7b74f4c6080292377a8c67c28be6e194329cad68";
[2024-03-11 13:11:01] production.ERROR: DEBUG (\Cache::get($mutex_name)): N;
[2024-03-11 13:11:01] production.ERROR: DEBUG (inside if (count($fetch_command_pids) > 0 && !\Cache::get($mutex_name)))
[2024-03-11 13:11:01] production.ERROR: DEBUG ($fetch_command_pids): a:1:{i:0;s:5:"21352";}
[2024-03-11 13:11:01] production.ERROR: DEBUG (count($fetch_command_pids)): 1
[2024-03-11 13:11:01] production.ERROR: DEBUG (Kill Line 128!!!!!!!!!!!!!!!!!)

```

So. mutex name definitely has value, but cache mutex is not being stored or recovered.

I cleared cache manually and everything behaves the same.

Not sure why cache would not save, but definitely nothing clears it because I tested the cache itself with something like this:
`\Cache::put('test_increment', \Cache::get('test_increment', 0) + 1, 10);`

And the cache with test incrementation works fine.

**Comment by freescout-helpdesk** [comment] 2024-03-11 13:10
Yes, strange. Are you using Docker or Cloudron?

Try to store some value in the cache and get it after that to check if FreeScout is able to store values in the cache:
```
\Cache::put('key', 'value1234567', \Carbon\Carbon::now()->addMinutes(10));
echo \Cache::get('key');
```

Also try to search stored value directly in the folder: `grep -rls value1234567 /storage/framework/cache`

**Comment by borgarlie** [comment] 2024-03-15 11:15
Have you found out anything more?

We are currently investigating a similar issue as well. But to us it seems to work most of the time, but sporadically it just kills the process. We know this happens in the exact same place by logging around `shell_exec('kill '.implode(' | kill ', $fetch_command_pids));`. However, the fetch will not start again until after the FETCH_MAX_EXECUTION_TIME (we confirmed this by logging timings and trying to change this value), and it is always the same behaviour.

**Comment by borgarlie** [comment] 2024-03-18 13:53
When this code is executed, there is supposed to be created a mutex.
```
$schedule->command('<command>')->withoutOverlapping();
```

Has anyone been able to inspect this mutex?

The following code:
```
$mutex_name = $schedule->command('<command>')
                ->skip(function () {
                    return true;
                })
                ->mutexName();
$mutex_value = Cache::get($mutex_name);
```
Always gives null. Same if we do `Cache::has()`. It will always give false value.

I don't really know how to inspect the file cache manually. So if anyone knows how to do that it might help too.
I tried switching to redis cache for easier inspection, but using env variables for setting CACHE_DRIVER etc did nothing.

**Comment by grrinch** [comment] 2024-03-18 15:06
Hey @borgarlie - could you switch to fetching every 3 minutes and see if this is solving your issue, too?

Like I said, if I have it check every 5 and more minutes, then the mutex gets messed up and doesn't set. However, if I set it to every 3, 2 or 1 minutes, then it works fine.

It would be great to have a confirmation on this.

**Comment by borgarlie** [comment] 2024-03-19 09:34
We have found out what the issue is.

The code that finds the mutex name:
```
// The name of the command here must be exactly the same as below!
// Otherwise long fetching will be killed and won't run longer than 1 mintue.
$mutex_name = $schedule->command($fetch_command_name)
    ->skip(function () {
        return true;
    })
    ->mutexName();
```
Actually creates a separate command, with a different mutex.
Since this command doesn't do anything, there is no mutex set and the test `Cache::get($mutex_name);` is always false, which means the real fetching job gets killed. Our fetching jobs are almost always longer than 1 minute, so they get killed very often.

We verified this with the following command:
```
foreach ($schedule->events() as $event) {
    $rows[] = [
        $event->command ? $event->command : '',
        $event->expression ? $event->expression : '',
        $event->description ? $event->description : '',
        $event->mutex->exists($event) ? 'Yes' : '',
        $event->mutexName(),
    ];
}

$this->table([
    'Command',
    'Interval',
    'Description',
    'Has Mutex',
    'mutex',
], $rows ?? []);
```

We haven't found a good solution to this problem yet. But at least we know what the problem is.
It seems we can't use `$schedule->events()` before the fetch command is created in the kernel. The kernel is probably special in some way compared to other Commands.
Our temp solution for now will probably be to get the mutexName after the fetch command is made, store it in cache under `fetch_mutex_name`, get that value from cache and use it in the above check. It is not a very nice solution, but it will probably do the job for now. Hopefully someone with more knowledge of Laravel will be able to solve this in a better way.

**Comment by freescout-helpdesk** [comment] 2024-03-19 13:56
Fixed in the `master` branch and will be published in the next release.

**Comment by borgarlie** [comment] 2024-03-19 14:01
Hi,

Thanks for following up.

We see that you implemented the same change that I outlined above. However, we actually encountered some issues with that. Since the Command and Kernel code is ran in a lot of instances, we started getting issues with permissions for writing to the cache, since it uses file cache.

We haven't found a nice way to circumvent this yet.

**Comment by freescout-helpdesk** [comment] 2024-03-19 14:18
Make sure that the cron job user is not messing up file ownership and permissions.
https://github.com/freescout-helpdesk/freescout/wiki/Installation-Guide#-permissions-issue

**Closed** 2024-03-22 07:11 UTC
