### ISSUE TITLE
Workflow Module: Bug in Action "Email the customer"

### ISSUE THREAD

**Issue by ar-ml** [freescout-helpdesk/freescout#2967] opened 2023-05-02 16:38 UTC
**Steps to reproduce:**
1. Install workflow module
2. create new workflow with condition "New conversation created".
3. go to Actions, select "Email the customer"
4. click on "Customize" and enter the following text: "EXAMPLE TEXT", then save the changes.
5. Test it via the end-user-protal.

**Expected Behaviour:**
Customer will receive an email with content  "EXAMPLE TEXT", when submitting a ticket via End-user-portal.

**Wrong behaviour:**
Customer eceives an email with a copy of the message that he submitted via End-User-Portal, but  "EXAMPLE TEXT" does not show up anywhere in the email!

Please fix, thank you!
![image](https://user-images.githubusercontent.com/28296008/235729868-88e11cc0-7bcb-4763-ad6a-47038a7354c7.png)

**Comment by freescout-helpdesk** [comment] 2023-05-03 05:59
We can't reproduce the issue - customer received by email the text specified in the workflow "Email the Customer" action.

**Comment by ar-ml** [comment] 2023-05-12 19:19
I recorded a screen capture video for you that demonstrates the issue. Hope you can help me:

https://sharing.clickup.com/clip/p/t757404/0c38f255-4bc0-4c87-a519-f72419245037/screen-recording-2023-05-12-21:15.webm?open=true

**Comment by ar-ml** [comment] 2023-05-16 19:37
Can someone help here? Thx!

**Comment by freescout-helpdesk** [comment] 2023-05-17 05:49
So far we could not reproduce it. Maybe something is broken on your installation. Try to re-update your FreeScout using manual updating method: https://github.com/freescout-helpdesk/freescout/wiki/Updating-FreeScout#method-5-update-manually

**Comment by freescout-helpdesk** [comment] 2023-08-04 14:07
Are you using the latest version of FreeScout and Workflows Module?

**Comment by ar-ml** [comment] 2023-08-04 14:51
Yes:
Workflows Module Version: 1.0.49
Freescout Version 1.8.87

**Comment by leonpetak** [comment] 2023-08-08 07:00
Hello @freescout-helpdesk, could you please give us an update or advice on this case?
We are considering reinstalling Freescout completely but would love to hear if there are any other suggestions before doing so.

**Comment by ar-ml** [comment] 2023-08-10 12:15
@freescout-helpdesk
Sorry, I have to push this topic. It is blocking us a lot. 
Any idea how to solve this? Can I somehow help you debugging it?

I fear a complete re-installation of the server including freescout will not help much, since we already tried the manual update method...

Thanks for any help!

**Comment by freescout-helpdesk** [comment] 2023-08-10 13:59
> So far we could not reproduce it.

You need to find someone who can debug it on your server.

**Comment by ar-ml** [comment] 2023-08-10 16:11
@freescout-helpdesk  thx for your answer.

@leonpetak is our Linux Admin. He might be able to debug it on our server, but can you give us a hint on how to debug it?
We tested it a hundred times with different settings but we did not see any pattern.
So are there any logfiles where we could see what exactly happens in the background when the workflow is triggered?
Could it be connected to the German language translation?
Could something on our server cause the issue?
Should we try to modify the PHP code of the workflows module?
Can you tell me where in the code the predefined text is inserted into the email that is being sent to the customer by the workflow module?
Where would you look first?

**Comment by freescout-helpdesk** [comment] 2023-08-16 05:58
We'll close this. Let us know if you'll find the reason of the issue on your FreeScout instance.

**Closed by freescout-helpdesk** 2023-08-16 05:58 UTC
