### ISSUE TITLE
Wrong ordering of closed issues

### ISSUE THREAD

**Issue by gino0631** [freescout-helpdesk/freescout#2191] opened 2022-09-02 14:04 UTC
By default, issues in the "Closed" folder are ordered descending by their Closed date, so recently closed issues should be listed first. While it is possible to find them on the first page, the order is wrong:
![image](https://user-images.githubusercontent.com/13659309/188157304-0f168df2-f6cc-42a1-8778-f1ca7b3cc265.png)

Changing the order to ascending seems to list the issues in the correct order:
![image](https://user-images.githubusercontent.com/13659309/188157974-30c4bc23-d947-4f83-bbcb-207038cf5722.png)

though after clicking "Next Page" the order gets reverted back to descending:
![image](https://user-images.githubusercontent.com/13659309/188161296-d6101649-9e6f-4d28-bb45-37b040fdffe6.png)

Environment:
FreeScout: 1.8.21
DB: PostgreSQL 12.11
PHP: 7.4.30

**Comment by freescout-helpdesk** [comment] 2022-09-03 04:58
This issues has already been fixed. Are you using the latest version of FreeScout?

**Comment by gino0631** [comment] 2022-09-03 12:19
Yes, I was using 1.8.21, and now updated to 1.8.22. The issue is still present, so it's not the same as #1965.

**Comment by freescout-helpdesk** [comment] 2022-09-03 13:49
We can't reproduce the issue. Also works fine on demo.freescout.net

![2022-09-03_16-48-29](https://user-images.githubusercontent.com/40499291/188273379-bb4aefcb-5ff4-4d7a-8f91-1bbaef3e9431.png)

**Comment by gino0631** [comment] 2022-09-03 14:05
OK, I'll try to debug the code. It is clear that some (but not all) issues are in the wrong order, but I haven't identified what is causing that. Maybe it has something to do with PostgreSQL.

As for the second part, when you change the order to ascending, and go to the next page, does the order stays ascending, or changes back to descending (as I observed)?

**Comment by freescout-helpdesk** [comment] 2022-09-03 14:11
> As for the second part, when you change the order to ascending, and go to the next page, does the order stays ascending, or changes back to descending (as I observed)?

The ordering changes back. This issue we can confirm.

**Comment by gino0631** [comment] 2022-09-03 22:13
Thanks!

As for the first part, I have checked the database and found out that those conversations that appear at the beginning in an incorrect order do not have a `closed_at` date set (i.e. `SELECT * FROM conversations WHERE closed_at IS NULL` return them all). Dates in "Closed" column are visible of course, and also when viewing the conversation messages. Do you have an idea what are the reasons for `closed_at` date being `null`?

**Comment by freescout-helpdesk** [comment] 2022-09-04 04:42
Are you using API & Webhooks module?
Are you using any non-official modules?

**Comment by gino0631** [comment] 2022-09-04 11:07
> Are you using API & Webhooks module?

No.

> Are you using any non-official modules?

No.

These issues were closed between 2020-09-21 and 2021-07-14. I can't identify how they differ from those that have `closed_at` date set. I think I'll just update the `conversations` table by setting the dates from `threads` for now.

**Comment by freescout-helpdesk** [comment] 2022-09-09 06:55
Pagination issue has been fixed in the `maser` branch.

We could not find a reason why `closed_at` may be not set.

**Closed by freescout-helpdesk** 2022-09-09 06:55 UTC

**Comment by jamieppuk** [comment] 2023-02-21 12:01
We have been experiencing the same issue where the conversation order is incorrect in the Closed folder due to 'closed at' being null for some tickets.

We can recreate this by manually create a new conversation with the "status after replying" setting set to "Closed"
As soon as the new conversation is sent it is set to Closed but the 'closed at' field is not set.

Also when creating a new conversation, if you manually select 'send and stay on same page' (or this is already set by default) it does not stay on the new conversation page after sending, it goes back to the folder (Draft) instead- I mention this in case it is related somehow
