### ISSUE TITLE
When merging conversations, the preview text should be handled in better way

### ISSUE THREAD

**Issue by mahavirn** [freescout-helpdesk/freescout#3528] opened 2023-11-14 11:41 UTC
Hi @freescout-helpdesk,

There is an issue with how the merge function works.

We have the End User Portal enabled, allowing customers to view their tickets there.

The problem arises when, for instance, we have ticket A and ticket B. If ticket B's last comment is an internal note (using the Notes feature), the conversation table's `preview` column is updated with that text. However, this is intended for internal users only.

The issue occurs when we merge Ticket B into A; the preview column value is not updated. As a result, internal notes become visible to our "End Users" when tickets are merged, and the merged ticket's last response (thread) was an internal note.

This is visible on `My Tickets` Page on End User Portal.

<img width="1280" alt="Screenshot 2023-11-14 at 5 11 06 PM" src="https://github.com/freescout-helpdesk/freescout/assets/118246547/05b478d0-00da-43ce-b1a4-21852d1beff9">

**Comment by freescout-helpdesk** [comment] 2023-11-14 13:08
We can't reproduce the issue. Are you using the latest version of FreeScout and End-User Portal Module?

**Comment by mahavirn** [comment] 2023-11-14 13:16
My FreeScout Version is : 1.8.104
End User Portal Version is: 1.0.67

**Comment by freescout-helpdesk** [comment] 2023-11-14 13:18
Can you reproduce the issue on demo.freescout.net?

**Comment by mahavirn** [comment] 2023-11-14 13:39
Hi,
Which account can i use to access end-user portal, as when i am using mine, its giving error: "Unable to send email"

**Comment by freescout-helpdesk** [comment] 2023-11-14 17:13
It's not possible to authorize as a customer on demo.freescout.net

Try to do the following:
1) Add a note to some conversation.
2) Check if this note is visible to the customer in the Tickets list in the End-User Portal.

**Comment by mahavirn** [comment] 2023-11-14 17:18
Hi @freescout-helpdesk 

i have completed point #1. how can i access End-user portal without login: https://demo.freescout.net/help/1321731726

**Comment by freescout-helpdesk** [comment] 2023-11-14 17:34
![2023-11-14_20-33-48](https://github.com/freescout-helpdesk/freescout/assets/40499291/848b6878-24ad-45c1-9b51-cb095995c3f1)

The issue you are describing has been fixed in the End-User Portal Module long time ago. It looks like you still have the old code. Try to re-install the module.

**Closed by freescout-helpdesk** 2023-11-14 17:34 UTC

**Comment by mahavirn** [comment] 2023-11-14 17:42
Hi @freescout-helpdesk 

Can you check your customer portal now?

Do you see 2 tickets there?
