### ISSUE TITLE
Time Tracking Module doesn't stop running unless you manually pause it.

### ISSUE THREAD

**Issue by andrewlimaza** [freescout-helpdesk/freescout#726] opened 2020-09-08 02:45 UTC
Hi there,

I've purchased the Time Tracking module, it seems that the timer will run in the background automatically even when a ticket has been replied to and is in 'pending' status. So some tickets show that it's been hours.

How can I get help resolving this? I'd like to only track time while someone on our team is actively working on the ticket or left that tab open and to stop tracking time when the ticket isn't open.

Freescout version: 1.5.12

<img width="1047" alt="Screen Shot 2020-09-08 at 04 44 08" src="https://user-images.githubusercontent.com/12629136/92427921-0a60fd80-f18e-11ea-87aa-1dec3735f371.png">

**Comment by freescout-helpdesk** [comment] 2020-09-08 05:28
User need to close the tab with the conversation to stop the timer.

**Comment by andrewlimaza** [comment] 2020-09-08 09:09
@freescout-helpdesk if I close Freescout entirely, the time tracking should stop right? Also when I'm not actively viewing a ticket?

Both cases it hasn't, for example: I've replied, went to bed, woke up and then the timer has a few hours on it for a ticket (when a customer has replied).

**Comment by freescout-helpdesk** [comment] 2020-09-08 09:11
Check background jobs in the Manage >> System.

**Comment by andrewlimaza** [comment] 2020-09-09 06:32
Thanks, there's no background jobs. I've noticed that if the customer replies the timer starts again. Is there a way to make it only a support engineer/specific set of user's can control the timers?

It should only be the people providing the support

**Comment by andrewlimaza** [comment] 2020-09-09 06:33
It'd be nice that the timer gets paused once you press reply and the ticket status changes to pending, or when you view another ticket.

**Comment by andrewlimaza** [comment] 2020-09-14 13:41
Hi any update? This actually threw out our time tracking badly. It says our support agent 'worked' 128 hours in the past week. Because when a customer replies to the email it starts tracking again and it shouldn't do this - it should only track when someone from our team is working on the ticket, right?

**Comment by andrewlimaza** [comment] 2020-09-14 13:41
It says a customer has spent 4 days on a ticket, which is definitely not the case 👎

**Comment by freescout-helpdesk** [comment] 2020-09-15 06:17
We can't reproduce the issue on our end.

**Comment by andrewlimaza** [comment] 2020-09-15 08:20
Does this rely on cron jobs or anything else? Where can I start looking into this/debugging?

**Comment by freescout-helpdesk** [comment] 2020-09-15 08:28
Yes, timer is stopped by background job. Also check Manage > Logs > App Logs

**Comment by andrewlimaza** [comment] 2020-09-15 08:34
This is what I have under "Queue Jobs log" - sh: ps: command not found

**Comment by freescout-helpdesk** [comment] 2020-09-15 08:36
This is the reason. You need to install `ps` command on your server.
```
apt-get install -y procps
```

**Comment by freescout-helpdesk** [comment] 2020-09-16 09:32
Have you managed to solve the issue?

**Comment by andrewlimaza** [comment] 2020-09-16 11:06
It does seem better but not 100% there yet. I did a fresh install on Digital Ocean (using cloudron.io) and ensured everything is correct - cron jobs, dependencies etc. (Same domain name, just on a dedicated server now - I was previously on Siteground which didn't allow this to be installed).

I noticed that the timer still runs if you view a 'pending' ticket but don't reply and then stop viewing this ticket.

There are no warnings in the log files.
![Screen Shot 2020-09-16 at 13 05 52](https://user-images.githubusercontent.com/12629136/93329343-5dd1ec00-f81d-11ea-877a-bdb375e35221.png)

**Comment by andrewlimaza** [comment] 2020-09-16 11:07
I am still running a few more tests but it seems some of the cases, it does pause now.

**Comment by Filoz** [comment] 2020-09-16 15:14
Hi, as reported in #592 , I have the same problem.

I have procps already installed

**Comment by andrewlimaza** [comment] 2020-09-17 07:54
I just logged in this morning, this ticket has no reply (but was previously opened yesterday). Closed Freescout from my browser, went to unassigned.

As you can see its 20 hours running idle.

![Screen Shot 2020-09-17 at 09 52 45](https://user-images.githubusercontent.com/12629136/93436838-9b8d4e00-f8cb-11ea-9b38-3f52a0201e48.png)

**Comment by freescout-helpdesk** [comment] 2020-09-17 13:26
Is System > Status ok?

Nothing in laravel.log?

**Comment by andrewlimaza** [comment] 2020-09-17 13:50
`SQLSTATE[42S02]:` Base table or view not found: 1146 Table '879d7eb1b92127b9.timelogs' doesn't exist (SQL: select * from `timelogs` where `conversation_id` = 3 and `finished` = 0 limit 1) {"userId":2,"email":"removedthis","exception":"[object] (Illuminate\\Database\\QueryException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 Table '879d7eb1b92127b9.timelogs' doesn't exist (SQL: select * from `timelogs` where `conversation_id` = 3 and `finished` = 0 limit 1) at /app/code/vendor/laravel/framework/src/Illuminate/Database/Connection.php:664, Doctrine\\DBAL\\Driver\\PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 Table '879d7eb1b92127b9.timelogs' doesn't exist at /app/code/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:79, PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 Table '879d7eb1b92127b9.timelogs' doesn't exist at /app/code/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:77)`

I removed my email for privacy reasons.

**Comment by andrewlimaza** [comment] 2020-09-17 13:51
This error was from yesterday, it no longer happens. I think this was when I tried to view the reports for timetracking and there was no data at the time.

**Comment by freescout-helpdesk** [comment] 2020-09-20 12:55
Can you give access to the droplet to check it? support@freescout.net

**Comment by freescout-helpdesk** [comment] 2020-10-28 05:48
Closing for no activity.

**Comment by freescout-helpdesk** [comment] 2020-11-21 06:53
The issue has been fixed in the Time Tracking Module v1.0.4

**Closed** 2020-12-25 07:38 UTC
