### ISSUE TITLE
Workflow does only work when setting "Apply to Previous" and saving it again

### ISSUE THREAD

**Issue by githubuser-112** [freescout-helpdesk/freescout#3095] opened 2023-06-09 16:27 UTC
Hey,

we have a workflow that should close all tickets that start with "Fwd:" so tickets created by forwards get closed automatically.

Unfortunately this does not work automatically. When there is such a mail in the inbox though and we set "Apply to Previous" and save the workflow, it works fine.

See screenshots of the message and the workflow settings:
![Workflow-Settings-1](https://github.com/freescout-helpdesk/freescout/assets/134635748/3b15d897-252f-40dc-aee1-b8a27b17d291)

![Workflow-Settings-2](https://github.com/freescout-helpdesk/freescout/assets/134635748/5a47103a-c8b9-45fc-9c8f-c3977303091a)

![Workflow-Settings-3](https://github.com/freescout-helpdesk/freescout/assets/134635748/e2cb653e-a6ec-4a08-bb09-31757e29697d)

![Forwarded-message](https://github.com/freescout-helpdesk/freescout/assets/134635748/9008a1ed-b218-4dfe-af8c-5353af694124)

PHP version: 8.2.6
FreeScout version: 1.8.80

**Comment by githubuser-112** [comment] 2023-06-14 15:07
We followed all of the steps of _"Method 5. Update manually"_ but it still does not work. "Migrate DB" responded "Nothing to migrate" by the way. 

How did the other party reinstall the application without losing everything?

**Comment by freescout-helpdesk** [comment] 2023-06-22 06:25
When you use "Method 5. Update manually" you are updating the FreeScout without losing data.
So the issue need to be investigated on your server.

**Comment by githubuser-112** [comment] 2023-07-05 19:53
We did that and did not lose any data, so the manual update went without problems. It just did not solve the problem.

In the last two weeks we noticed the following: The workflow does get triggered, but with random delay. Please see the following screenshot. The workflow should be processed the moment the ticket gets created, not 51 minutes after for example. On other tickets, these time frames are always between a few minutes up to an hour.

![screenshot](https://github.com/freescout-helpdesk/freescout/assets/134635748/e232baf8-3068-4901-a74e-2819c3776894)

I wanted to recreate the same workflow on your demo-freescout, but unfortunately it is not permitted. Did you recreate the workflow and it works fine on your end?

**Comment by freescout-helpdesk** [comment] 2023-07-06 12:07
> The workflow does get triggered, but with random delay.

It means you have problems with background jobs: https://github.com/freescout-helpdesk/freescout/wiki/Background-Jobs

**Comment by githubuser-112** [comment] 2023-07-10 23:09
Background processes seem to run fine. The Workflow still does not get executed at all if the "Apply to Previous"-Setting is disabled. All other workflows work fine and get called immediately on receiving an email or changed status etc.

**Comment by freescout-helpdesk** [comment] 2023-07-17 05:24
The issue need to be investigated on your FreeScout instance as we can't reproduce it.

**Comment by freescout-helpdesk** [comment] 2023-07-17 17:21
Fixed in Workflows Module v1.0.47

**Closed by freescout-helpdesk** 2023-07-17 17:21 UTC

**Comment by githubuser-112** [comment] 2023-07-17 18:44
I´m really sorry, but we just ran the update and it still is not working. Thanks for double checking that there really is something not working as intended.
