### ISSUE TITLE
Incorrect email subject decoding

### ISSUE THREAD

**Issue by ilyakonovalenko** [freescout-helpdesk/freescout#3066] opened 2023-06-01 06:01 UTC
Something happened to email subject decoding after 1.8.76. Probably because of #2987.

UTF8 encoded subjects are now look this way:
![изображение_2023-06-01_080101972](https://github.com/freescout-helpdesk/freescout/assets/63669538/0ae8d60f-1558-46e0-9743-38ffd22d4783)

**Comment by freescout-helpdesk** [comment] 2023-06-01 06:02
Could you please attach email headers.

**Comment by ilyakonovalenko** [comment] 2023-06-01 07:43
Here are some headers:

```
Subject: =?utf-8?B?0JLRi9C/0LjRgdC60LAg0LfQsCDQv9GA0L7RiNC10LTRiNC4?=
 =?utf-8?B?0Lkg0LzQtdGB0Y/RhiDQv9C+INCe0J7QniAi0JjQmtCh0KTQkNCZ0JLQ?=
 =?utf-8?B?mNCa0KEi?=
Content-Type: multipart/mixed;
	boundary="--boundary_9907_9c6434c1-24c5-4378-aeba-b3b36a9f5ccf"
Message-ID: <959223db-50d1-4e62-a900-66c5bd36a092@WRUDC1M021.brc.local>

----boundary_9907_9c6434c1-24c5-4378-aeba-b3b36a9f5ccf
Content-Type: text/html; charset="utf-8"
Content-Transfer-Encoding: base64
```

Same emails were decoded correctly before that update.

**Comment by freescout-helpdesk** [comment] 2023-06-01 08:51
We can't reproduce the issue.

What FreeScout version are you using?

Are you using modern Microsoft OAuth IMAP authentication or `APP_NEW_FETCHING_LIBRARY` parameter in .env file?

Can you send a sample email to support@freescout.net

**Comment by freescout-helpdesk** [comment] 2023-06-01 09:29
Should be fixed in the `master` branch now.

**Closed** 2023-06-03 09:33 UTC
