### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by alexsokolik** [freescout-helpdesk/freescout#3980] opened 2024-04-18 13:10 UTC
How to make sure that when the application is addressed to the agent and the agent closes it when new applications from the same client are opened, the application is assigned?

**Comment by freescout-helpdesk** [comment] 2024-04-19 06:22
Maybe you are talking about https://github.com/freescout-helpdesk/freescout/issues/3974

**Comment by Sokolset** [comment] 2024-04-24 22:20
Hi, I have 2 problems, 1 I received a ticket and I assign it to the agent, he answered the ticket, clicked the send button and the ticket went to the folder, unassigned, I want the ticket to remain with the agent until the closure of all the correspondence. 2 The problem is due to the fact that when the application was assigned to the agent, he worked it out and closed the repeated appeal of the same client after closing, he sends a ticket to the agent and I would like that in the public folder not assigned received zero reset the agent from this application!

**Comment by freescout-helpdesk** [comment] 2024-04-26 04:39
It's quite hard to understand what you are saying. Maybe you need this:

![2024-04-26_07-39-02](https://github.com/freescout-helpdesk/freescout/assets/40499291/fbbf2090-efd5-487d-b3fe-3f9c21db9d07)

**Comment by Sokolset** [comment] 2024-04-26 13:32
Here I described the whole problem   https://disk.yandex.ru/i/7b6aG9BWYCq2zg

**Comment by freescout-helpdesk** [comment] 2024-04-26 13:37
1. Use "Default Assignee" option in Mailbox settings.
2. Try to use Workflows Module.

**Comment by Sokolset** [comment] 2024-04-26 16:08
Tell me, can you do it in the all folder so that only open applications can be seen ? If not, how can you make such a folder so that it shows applications of all folders but only open ones?
![Uploading 2024-04-26_21-01-50.png…]()

**Comment by freescout-helpdesk** [comment] 2024-05-05 06:55
Unfortunately not.

**Closed by freescout-helpdesk** 2024-05-05 06:55 UTC

**Comment by Sokolset** [comment] 2024-08-08 06:03
At the moment, we have such a problem before the installation of the last update, messages are not sent to telegram WhatsApp mail, we rolled back to the last update and worked further, but the day before yesterday we stopped sending in all channels and in mail and receiving messages. Tell me if I can hire a person to solve problems or help you because our support hasn't been working for 3 days

**Comment by Sokolset** [comment] 2024-08-08 06:08
Could you help us with a specialist for support?
