### ISSUE TITLE
Wrong charset in copy of sended email (IMAP Folder To Save Outgoing Replies)

### ISSUE THREAD

**Issue by marcinkaminski** [freescout-helpdesk/freescout#1581] opened 2021-12-14 09:46 UTC
FS 1.7.24 latest

In inbox -> connection settings -> Fetching emails -> IMAP Folder To Save Outgoing Replies
I have `INBOX.Sent` which saves copy of sended email in my Sent folder on IMAP.

But that email have wrong charset:
Content-Type: TEXT/html; CHARSET=US-ASCII and in body <html lang="en">.
We have everything in UTF8 in freescout but our language is polish (pl) so char ń becomes Å„ in that email.

**Comment by maltem-za** [comment] 2022-03-18 14:09
Duplicate of #1296 

I can confirm this is happening with v1.8.9 on PHP 8.1.3

**Closed** 2022-03-18 14:13 UTC
Labels: help wanted

**Comment by MarcoWel** [comment] 2022-04-21 00:31
Hi,
Why is this issue closed? The bug is still present in version 1.8.12 released some days ago.

- Message sent to customer: Correct Header **Content-Type: multipart/alternative;**
- Message copy stored in Sent folder: Wrong Header **Content-Type: TEXT/html; CHARSET=US-ASCII**
