### ISSUE TITLE
Closed At field not being set

### ISSUE THREAD

**Issue by jamieppuk** [freescout-helpdesk/freescout#2751] opened 2023-02-21 12:02 UTC
hi, this relates to...
https://github.com/freescout-helpdesk/freescout/issues/2191

We have been experiencing the same issue where the conversation order is incorrect in the Closed folder due to 'closed at' being null for some tickets.

We can recreate this by manually create a new conversation with the "status after replying" setting set to "Closed"
As soon as the new conversation is sent it is set to Closed but the 'closed at' field is not set.

Also when creating a new conversation, if you manually select 'send and stay on same page' (or this is already set by default) it does not stay on the new conversation page after sending, it goes back to the folder (Draft) instead- I mention this in case it is related somehow

**Comment by freescout-helpdesk** [comment] 2023-02-21 13:23
We can't reproduce the issue. Are you using the latest FreeScout version?

**Comment by jamieppuk** [comment] 2023-02-21 13:30
1.857 I can update if it's helpful ?

**Comment by jamieppuk** [comment] 2023-02-21 13:36
just to recap, to reproduce i am...

1) Edit Mailbox > set "Status After Replying" to Closed
2) click 'new conversation' envelope icon
3) fill in ticket and click 'send' with 'send and stay on page' set by default
4) ticket is emailed, status set to Closed without the 'Closed at' field being set (null), page goes back to Draft folder

**Comment by freescout-helpdesk** [comment] 2023-02-21 14:19
Fixed in the `master` branch.

**Comment by jamieppuk** [comment] 2023-02-24 11:39
many thanks, sorry my technical knowledge is not so great, presumably this will be in the next update version release and then teh change will come into effect when we update to the new version?

**Comment by freescout-helpdesk** [comment] 2023-02-24 11:40
yes

**Closed** 2023-02-24 11:46 UTC
