### ISSUE TITLE
A canceled email was sent and is now displayed incorrectly in Outgoing Emails

### ISSUE THREAD

**Issue by il2020** [freescout-helpdesk/freescout#3300] opened 2023-08-24 13:41 UTC
I wrote a reply to the costumer and clicked "Send Reply". Then I saw an error in my text and clicked "Undo" in the notification that appeared. Then corrected the error and clicked "Send Reply" again.

Now if you look at the sent emails on my reply, it shows two lines, and the first of them without the email.

![Screenshot_20230824_162258](https://github.com/freescout-helpdesk/freescout/assets/77854832/55b24f12-fab2-4192-867c-4880b9aa0e04)

But if you look the emails in Log Records, both lines here contain emails.

![Screenshot_20230824_162431](https://github.com/freescout-helpdesk/freescout/assets/77854832/891b59e2-29d0-4f85-bcf5-06e53bb1ad86)

Here is a part of code from the Outgoing Emails window:

```html
<table class="table table-striped">
  <tbody>
    <tr>
      <th>Customer</th>
      <th>Remarks</th>
      <th>Date</th>
      <th>Status</th>
    </tr>
    <tr>
      <td rowspan="2">victoria@example.com</td>
      <td>&nbsp;</td>
      <td>Aug 24, 2023 16:12:10</td>
      <td>
        <span class="">Accepted for delivery</span>
      </td>
    </tr>
    <tr>
      <td>&nbsp;</td>
      <td>Aug 24, 2023 16:11:59</td>
      <td>
        <span class="">Accepted for delivery</span>
      </td>
    </tr>
  </tbody>
</table>
````

PHP version: 7.4.33
FreeScout version: 1.8.90

**Comment by freescout-helpdesk** [comment] 2023-08-25 06:49
We can't reproduce the issue.

**Comment by il2020** [comment] 2023-08-25 11:46
Ok. Apparently, this is a rare problem. In most cases, canceling the send and resending works correctly, and there is no problem with the address display.

**Comment by il2020** [comment] 2023-09-04 09:08
I am now experiencing the same problem again.

![image](https://github.com/freescout-helpdesk/freescout/assets/77854832/b44adce8-309e-44dd-b31b-a4d33c45a252)

I think it happens if you cancel the send not immediately when the notification appears, but after a few seconds. Perhaps the sending starts a bit before the notification disappears.

PHP version: 7.4.33
FreeScout version: 1.8.95

**Comment by freescout-helpdesk** [comment] 2023-09-05 06:46
It happens when you undo sending, quickly edit the draft and send again.

**Comment by freescout-helpdesk** [comment] 2023-09-05 07:34
Fixed in the `master` branch.

**Closed** 2023-09-08 11:37 UTC
