### ISSUE TITLE
Saved reply with First name (and maybe others) does'nt work

### ISSUE THREAD

**Issue by rabbidiesel** [freescout-helpdesk/freescout#3538] opened 2023-11-21 17:56 UTC
Hi,

I am not sure if this a featur request, but for some reason I couldnt get to https://freescout.net/request-feature/ anyway.

I have Saved Reply Model installed and I set up some reply with  {%customer.firstName%}, variable in them.

The issue is that it never pulls the customers name, even when I know there is a name connected to the email.
I also have the Customers Management (CRM) model that allows me to put all customer info in it.

Please Advise if I need to post this question somewhere else.

Thanx,

PHP version: 7.4.16
FreeScout version: 1.8.109
Database: Mysql (8.0.27-0ubuntu0.21.04.1)
Are you using CloudFlare:  No

**Comment by rabbidiesel** [comment] 2023-11-21 18:00
Just to clarify, this issue only happens on a new email. It does not happen on a reply.

**Comment by freescout-helpdesk** [comment] 2023-11-21 18:02
We can't reproduce the issue. Can you send a screenshot.

**Comment by freescout-helpdesk** [comment] 2023-11-23 05:24
Fixed in the `master` branch and will be published in the next release.

**Closed** 2023-12-02 05:20 UTC
