### ISSUE TITLE
Telegram + Workflow

### ISSUE THREAD

**Issue by ri-ees** [freescout-helpdesk/freescout#2329] opened 2022-10-14 17:57 UTC
Hi, I believe I have found two glitches/bugs, not sure if related or not with each other when using Telegram Integration and Workflows together.

This one in particular started to happen after adding "2" workflows to a mailbox, and after triggering both workflows. When a Workflow is triggered, where the action is "Email the Customer", sometimes, the text being sent is not the one specified in that action. Instead, Workflow will simply copy and paste the text the user sent in the first place.

Eg... User sends the message "Hello!". Workflow is configured to reply with "Hi." Workflow replies "Hello!" instead, copying and pasting what the user sent. The same happens with longer phrases, copying and pasting as a response what the User sent.

**Comment by freescout-helpdesk** [comment] 2022-10-15 07:21
Better to create separate issues for different topics. Which module do you mean under "Telegram": Telegram Notifications or Telegram Integration?

**Comment by ri-ees** [comment] 2022-10-15 07:25
I edited the first message to keep it clean. Answering your question, Telegram Integration.

**Comment by freescout-helpdesk** [comment] 2022-10-15 08:14
Could you please attach screenshot of the conversations for Workflow issue.

**Comment by ri-ees** [comment] 2022-10-15 19:48
Screenshots attached. I had to reproduce it again. So, two workflows. The first one worked as expected, sending the lorem text visible partially in the screenshot of the Telegram app.

In the second workflow, the same exact workflow uses the same rules but with a different keyword to trigger it, and replies to the same message the user sends.

And now, after I went to take a screenshot of workflow number two, I found out the text of "Email the Customer" was blank (the text disappeared as if I didn't write anything on it, nor saved it). I replicated this behavior a second time just to be sure it wasn't a human mistake.

![Screenshot 2022-10-15 at 20 30 44](https://user-images.githubusercontent.com/36930509/196004699-8b850c54-604f-4bf6-ae52-8ce75be9e5c4.png)
![Screenshot 2022-10-15 at 20 30 59](https://user-images.githubusercontent.com/36930509/196004700-eb8a2584-d915-436f-b3a8-9967c7022673.png)
![Screenshot 2022-10-15 at 20 30 54](https://user-images.githubusercontent.com/36930509/196004702-4b2404d8-9fb3-4166-977e-9b50697f6ba8.png)
![20221015_192240764_c727](https://user-images.githubusercontent.com/36930509/196004387-a56c6991-9b08-48d2-837a-eb44d1668fad.jpg)

**Comment by freescout-helpdesk** [comment] 2022-10-23 14:57
We can't reproduce the issue. Are you using any non-official modules?

What text are you entering for the second workflow? Try to view the source code of the second "Email the Customer" message:
![2022-10-23_17-54-18](https://user-images.githubusercontent.com/40499291/197399156-a66d2b84-8e9a-441c-b6a3-91fa9a3acb21.png)

Also check JavaScript errors in the browser console.

**Comment by ri-ees** [comment] 2022-10-25 04:27
Only official modules. Any kind of text, even the most simple one will trigger that behavior. I also tried by testing the workflow number 2, before trying workflow number 1 (which was the one working). And when I tried, it was the workflow number 1 that was not working correctly this time. I also tried to change to the php version 8.1, same behavior. Workflows triggered manually are also working. Not sure it could help but also tried to disable, uninstall license and module, re-install, re-enable, re-activate license.

I found one error that is happening from time to time at different places on freescout. It's strange that it is only appearing from time to time.

![Screenshot 2022-10-25 at 04 29 44](https://user-images.githubusercontent.com/36930509/197682337-82824660-a18c-47cb-b7ec-ed141c856ff8.png)

**Comment by freescout-helpdesk** [comment] 2022-10-25 05:46
> I found one error that is happening from time to time at different places on freescout. It's strange that it is only appearing from time to time.

This can't cause the issue with workflow, but check Check Manage > Logs > App Logs.

**Comment by ri-ees** [comment] 2022-10-25 06:30
Doesn't seem to be related. This is the only error showing:

sha1(): Passing null to parameter #1 ($string) of type string is deprecated {"exception":"[object] (ErrorException(code: 0): sha1(): Passing null to parameter #1 ($string) of type string is deprecated at https://redacted.domain/public_html/Modules/TelegramIntegration/vendor/botman/botman/src/Messages/Incoming/IncomingMessage.php:92

**Comment by freescout-helpdesk** [comment] 2022-10-29 05:33
We'll close this till someone will be able to reproduce.

**Closed by freescout-helpdesk** 2022-10-29 05:33 UTC
