### ISSUE TITLE
Conversation can be assigned to admin, though admin is crossed off as hidden

### ISSUE THREAD

**Issue by ringe** [freescout-helpdesk/freescout#2343] opened 2022-10-25 07:44 UTC
The logged in user here (Meg) is Administrator and can assign themself:
![Screenshot 2022-10-25 at 09-37-43](https://user-images.githubusercontent.com/778570/197713683-b4bf1396-eb20-48c7-a280-fe4a96382852.png)

This is possible despite being crossed off as hidden from assign list:
![Screenshot 2022-10-25 at 09-36-52 Postboks rettigheter](https://user-images.githubusercontent.com/778570/197713536-25c3f678-115f-419e-b90f-a6e150cec59d.png)

**Comment by freescout-helpdesk** [comment] 2022-10-29 06:06
This is by design. User is always able to assign to himself. "Hide from Assign list" option hides the user for other users.

**Closed by freescout-helpdesk** 2022-10-29 06:06 UTC
