### ISSUE TITLE
Teams module + Workflows: no user notifications

### ISSUE THREAD

**Issue by ilyakonovalenko** [freescout-helpdesk/freescout#2159] opened 2022-08-16 13:51 UTC
When assign conversation to team via workflows, no notifications are sent to team members. I checked outgoing emails log, nothing in the list for the conversations.

**Comment by ilyakonovalenko** [comment] 2022-08-16 17:52
It seems "Send Email Notification" action is required. Am I correct? Is it correct if I first change assignee and then send email notification to current assignee?

**Comment by ilyakonovalenko** [comment] 2022-08-17 14:54
I just checked. "Send Email Notification" action to "Current assignee" does not send any notifications to team members. Also there is no way to set team for "Send Email Notification" action. Seems like a bug.

**Comment by freescout-helpdesk** [comment] 2022-08-18 08:03
We've checked - notifications are being sent to Team members. Maybe the issue was caused by these issues: https://github.com/freescout-helpdesk/freescout/issues/2138 Try to double check.

**Comment by ilyakonovalenko** [comment] 2022-08-18 16:45
It seems notifications are being sent if first assign to team and then send notifications to current assignee. 
However, there is no way to send notifications to team. Workflow marks incomplete and can not be activated.

**Comment by freescout-helpdesk** [comment] 2022-08-18 18:35
Could you please attach screenshots.

**Comment by ilyakonovalenko** [comment] 2022-08-19 08:22
For actions:
![image](https://user-images.githubusercontent.com/63669538/185576601-448620bf-e4a7-43d3-9e47-724f1399cfa0.png)
The same is for conditions.

**Comment by ilyakonovalenko** [comment] 2022-08-26 18:07
I reviewed the code. The issue happens because validateConditions() function uses:
```
$user = User::nonDeleted()->where('id' , $condition['value'])->first();
```
But team users are technically deleted, because their status is `3` which is out of `nonDeleted()` scope.

**Comment by ilyakonovalenko** [comment] 2022-09-02 20:21
After the latest Workflows update condition Assugned to user stopped working completely. It does not accept any values except normal users and unassigned... The condition worked fine for teams before update.

**Comment by freescout-helpdesk** [comment] 2022-09-03 04:54
> After the latest Workflows update condition Assugned to user stopped working for teams completely. It does not accept any values except normal users and unassigned... The condition worked fine for teams before update.

Workflows Module v1.0.26 and v1.0.27 don't include changes which may cause this.

```
--- a/Entities/Workflow.php
+++ b/Entities/Workflow.php
@@ -1372,7 +1372,7 @@ class Workflow extends Model
             return false;
         }
-        \Helper::backgroundAction('workflow.do_process', ['id' => $workflow->id]);
+        \Helper::backgroundAction('workflow.do_process', [$workflow->id]);
     }
@@ -1368,7 +1368,7 @@ class Workflow extends Model
     public static function maybeProcessInBackground($workflow)
     {
-        if (!$workflow->active || !$workflow->apply_to_prev) {
+        if (!$workflow->active || !$workflow->apply_to_prev || !$workflow->id) {
             return false;
         }

```

**Comment by ilyakonovalenko** [comment] 2022-09-03 05:06
> Workflows Module v1.0.26 and v1.0.27 don't include changes which may cause this.

Well, after update all workflows related to Assigned to user condition became incomplete and can not be activated. 
I will test it more. But it seems something changed in conditions validation function.

**Comment by ilyakonovalenko** [comment] 2022-09-03 05:09
I got it. There were my changes in order to make those conditions work for teams. Okay. 
Anyway, it seems some fix should be added in order to allow teams to be selected.

**Comment by freescout-helpdesk** [comment] 2022-09-03 05:15
It will be fixed in the next release of Teams module.

**Comment by freescout-helpdesk** [comment] 2022-09-03 05:51
Fixed in Teams Module v1.0.4

**Closed by freescout-helpdesk** 2022-09-03 05:51 UTC

**Comment by ilyakonovalenko** [comment] 2022-12-15 22:02
"Assigned to user" condition is not working again after the last Teams module update. It is now impossible again to select team as a value of the condition...

**Comment by freescout-helpdesk** [comment] 2022-12-16 06:01
Have you updated FreeScout to the latest version?

**Comment by freescout-helpdesk** [comment] 2022-12-16 06:05
We've now made the module to require FreeScout v1.8.40.
