### ISSUE TITLE
ics calendar attachments not displayed in MS Teams invitations

### ISSUE THREAD

**Issue by endoflevelboss** [freescout-helpdesk/freescout#2054] opened 2022-06-17 15:32 UTC
Is there any special feature that handles ics calendar attachments differently from other attachments? I can find the ics attachments stored in app/attachment but they are not at all displayed in the respective conversation. All other attachment types are displayed. Anything I can check or configure to make these attachments become visible?

Any pointer is highly appreciated. Thanks in advance.

**Comment by endoflevelboss** [comment] 2022-06-17 15:35
Sorry. Duplicate of #1412 and #1003

**Comment by endoflevelboss** [comment] 2022-06-17 23:52
Duplicate closed

**Comment by freescout-helpdesk** [comment] 2022-06-18 14:58
Can you send a test email to support@freescout.net

**Comment by endoflevelboss** [comment] 2022-06-18 15:08
Done. Thanks!

**Comment by freescout-helpdesk** [comment] 2022-06-18 15:13
The .ics file is received and can be downloaded.

![2022-06-18_18-12-42](https://user-images.githubusercontent.com/40499291/174444770-143e54f6-0a8a-486b-9fde-7c4b72d548cf.png)

**Comment by endoflevelboss** [comment] 2022-06-18 15:53
Weird. Checking the attachments table in the database shows that all (at least all I checked) ics attachments are in the database. They are also saved to the app/storage folder. However, they are still not displayed in the conversation. I'll try to dig a little deeper later.

Anything I can check in my particular installation? Can you think of any locale or other settings that could affect whether a file is displayed?

**Comment by freescout-helpdesk** [comment] 2022-06-18 16:17
It's hard to tell what may cause this. It need to be debugged.

**Comment by freescout-helpdesk** [comment] 2022-06-19 08:28
Try to find .ics attachment in `attachments` table and check `embedded` field. If embedded=`true` it means the attachment by some reason has been detected as embedded in the text of the message (like embedded image).

**Comment by endoflevelboss** [comment] 2022-06-20 07:49
Just checked. None of the ics files in the attachments table is embedded. mime_type is correctly set to "text/calendar".

Additionally, I double checked a few random attachments (embedded and non-embedded) with the original emails and all of them are correctly registered as well.

**Comment by freescout-helpdesk** [comment] 2022-07-06 06:17
Have you found a solution?

**Comment by endoflevelboss** [comment] 2022-07-06 07:16
AFK right now. I will continue to look into this hopefully next week when I‘m back to my desk.

**Comment by freescout-helpdesk** [comment] 2022-12-19 11:54
Duplicate of https://github.com/freescout-helpdesk/freescout/issues/1412

**Closed by freescout-helpdesk** 2022-12-19 11:54 UTC
Labels: help wanted
