### ISSUE TITLE
Team Folders don't show ticket count after update

### ISSUE THREAD

**Issue by Bergrad** [freescout-helpdesk/freescout#3005] opened 2023-05-11 10:56 UTC
PHP: 8.1.14
FreeScout: 1.8.76
Module Teams: 1.0.13

After updating to version 1.8.76, the number of tickets in the team folders is no longer displayed.

**Comment by freescout-helpdesk** [comment] 2023-05-11 11:08
Duplicate of https://github.com/freescout-helpdesk/freescout/issues/2998

**Closed by freescout-helpdesk** 2023-05-11 11:08 UTC
