### ISSUE TITLE
Problem with hide ticket not assigned

### ISSUE THREAD

**Issue by markusdolla89** [freescout-helpdesk/freescout#3843] opened 2024-03-01 22:16 UTC
Hi,
I was looking for a way to hide Tickets not assigned to that user, I found this: https://github.com/freescout-helpdesk/freescout/issues/701

It works well, however there is a problem, if the user starts creating a draft and then exits to resume it later, the user will be unable to resume the draft even if created by him.

**Comment by markusdolla89** [comment] 2024-03-01 22:46
Another bug: The user who can only see the conversations assigned to him, cannot start conversations, always gets the error: "Not enough permissions"

**Comment by freescout-helpdesk** [comment] 2024-03-02 12:44
Fixed in the `master` branch and will be published in the next release.

**Comment by markusdolla89** [comment] 2024-03-02 14:34
Hi, thank you very much! I also discovered a way to circumvent the system if the user only has permission to view his tickets. The user just needs to go to notifications, tick "Notify me when There is a new conversation", and he will receive an email for each conversation created by everyone. Maybe this can be solved by simply creating a way to block notification editing permissions, it could be done that only administrators can set notifications for users, I don't know, I'm also waiting for your reflection on the matter.

**Comment by markusdolla89** [comment] 2024-03-02 14:54
> Fixed in the `master` branch and will be published in the next release.

I have tested the changes, the draft problem has been resolved, but the user is still not able to start conversations, the "Not Enought Permissions" error always comes up. But I don't think there are any further permits to be granted.

**Comment by freescout-helpdesk** [comment] 2024-03-03 05:33
It should be fixed now in the `master` branch. Such users will receive notifications only for conversations assigned to them.

**Comment by markusdolla89** [comment] 2024-03-04 09:47
> It should be fixed now in the `master` branch. Such users will receive notifications only for conversations assigned to them.

Thank you!

**Comment by alberto464** [comment] 2024-03-04 13:01
> It should be fixed now in the `master` branch. Such users will receive notifications only for conversations assigned to them.

After applying this FIX, normal users, without ticket viewing limitations, when they try to access a conversation not assigned to them, receive the "Access Denied" error, they see them, but when they try to access it says that it is denied.

I did some tests and it seems that the problem is caused by this change: https://github.com/freescout-helpdesk/freescout/commit/911e1573225c17bba95adae4a028fa00fadfeca7#diff-b1934e93868d34dd182708708bf54321fabc4eb34139c5783f81120a30b463e9

**Comment by alberto464** [comment] 2024-03-04 13:56
Thank you!

**Closed** 2024-03-08 08:22 UTC
