### ISSUE TITLE
Getting 404 not found on modules/list

### ISSUE THREAD

**Issue by chatilaah** [freescout-helpdesk/freescout#2851] opened 2023-03-22 11:07 UTC
I have managed to get the Freescout application up and running on my web service and local machine, but I keep on getting the "404 Not Found (nginx)" when attempting to navigate to the Modules page.

Could this be a bug?

**Comment by freescout-helpdesk** [comment] 2023-03-22 11:17
Duplicate of https://github.com/freescout-helpdesk/freescout/issues/2850

**Closed by freescout-helpdesk** 2023-03-22 11:17 UTC
