### ISSUE TITLE
creating a new ticket writes "Re:" into mail subject

### ISSUE THREAD

**Issue by mokkin** [freescout-helpdesk/freescout#2509] opened 2023-01-04 10:37 UTC
When we are creating a new ticket on our own

![grafik](https://user-images.githubusercontent.com/2938748/210536768-4143577c-f0cb-43da-a990-98e342c6158d.png)

the customer is receiving an email as expected, but the subject of the email starts with "Re:". In my opinion this should be the beginning only when we are answering to an email.

**Comment by freescout-helpdesk** [comment] 2023-01-04 10:41
We can't reproduce the issue. Please send screenshots.
Are you using any non-official modules?

**Comment by mokkin** [comment] 2023-01-04 11:03
This is how it looks like in the Thunderbird Sent folder:

![grafik](https://user-images.githubusercontent.com/2938748/210541472-75f69167-a50b-4022-a02f-f40daca9aa27.png)

All of these four email conversations were started in Freescout and are not replies to an incoming email. As youc can see, all of them are starting with "Re:".

We started using Freescout two days ago and doen't use any official or unofficial modules yet.

**Comment by freescout-helpdesk** [comment] 2023-01-04 11:30
Try to find the original subject of those emails: https://www.combell.com/en/help/kb/where-can-i-find-the-mail-headers-in-thunderbird/

**Comment by ilyakonovalenko** [comment] 2023-01-04 12:17
Whan version are you using? I remember I faced the same issue when using one of the old versions. I can not reproduce the issue as well now.

**Comment by mokkin** [comment] 2023-01-04 12:44
Here is the (censored) source code of one:

```
Date: Tue, 03 Jan 2023 18:44:52 +0100
From: hallo@XXXXXX.de
Subject: Re: Auszahlungsdaten fehlen
To: info@XXXXXX.de
Message-ID: reply-1948-a877e5c061fafb9b@XXXXXX.de
MIME-Version: 1.0
Content-Type: TEXT/html; CHARSET=utf-8
```

We are on v1.8.46

**Comment by freescout-helpdesk** [comment] 2023-01-04 13:29
How does this message look in FreeScout?

**Comment by mokkin** [comment] 2023-01-04 13:33
Like this:
![grafik](https://user-images.githubusercontent.com/2938748/210566198-153e3d97-f3af-49cb-a6d2-7294fcf5fec1.png)

**Comment by freescout-helpdesk** [comment] 2023-01-04 13:38
And it's subject?

**Comment by mokkin** [comment] 2023-01-04 15:48
Oh sorry, I have forgotten to include this:

![grafik](https://user-images.githubusercontent.com/2938748/210594026-ece4430e-5e06-4872-9e4a-d36099f630b8.png)

**Comment by freescout-helpdesk** [comment] 2023-01-07 05:30
Have you installed FreeScout just now or updated from some old version?

**Comment by mokkin** [comment] 2023-01-08 20:58
I installed about a week ago v1.8.45 and updated once.

**Comment by mokkin** [comment] 2023-01-09 20:53
I've tested it again with the actual version and I can't reproduce it anymore. I'm closing this and I will reopen it, if it occurs again.

**Comment by kazuemon** [comment] 2023-02-07 15:19
I am experiencing the same problem in my environment.
Current version is 1.8.57. (I have updated several times from older versions.)

The first image is the Freescout screenshot, and the second is a part of the header of the actual email sent.

![2023-02-08 00_15_13](https://user-images.githubusercontent.com/12812934/217285237-2603e509-c48a-448e-bc70-5314b6a2cd52.png)
![2023-02-08 00_16_07](https://user-images.githubusercontent.com/12812934/217285249-16097817-bf99-4817-87d4-3682c63092f8.png)

If I should make another issue, I will make a new one.

**Comment by freescout-helpdesk** [comment] 2023-02-07 17:26
No need. We can't reproduce it. You may need to debug it yourself or find someone who can do it on your FreeScout instance: https://github.com/freescout-helpdesk/freescout/wiki/Hire-Developer

**Comment by kazuemon** [comment] 2023-02-07 18:23
I understand.

After additional checking, I found that the subject line of the email in the IMAP sent folder (the image shown earlier) and the subject line of the email actually sent to the recipient were different. The subject line of the actually sent email did not have a "Re:" in the subject line.

So, the cause of this problem may be the following part of "Save outgoing replies in the IMAP folder".

https://github.com/freescout-helpdesk/freescout/blob/6102bda4023ee8fe8aadf9dfcb99095a1ba16a16/app/Jobs/SendReplyToCustomer.php#L289

I will investigate this and make a pull request if I can fix it.

**Comment by freescout-helpdesk** [comment] 2023-02-22 12:11
Fixed in the `master` branch. Apparently you were checking emails in the Sent folder in your mailbox, not in the recipient's mailbox.

**Comment by ilyakonovalenko** [comment] 2023-02-22 12:31
> Apparently you were checking emails in the Sent folder in your mailbox, not in the recipient's mailbox.

No, it was in the forwarded copy recipient mailbox. Thanks for fixing.

**Closed** 2023-02-26 05:14 UTC
Labels: help wanted
