### ISSUE TITLE
Fetching Problems: Error: Unexpected characters at end of address

### ISSUE THREAD

**Issue by Servery** [freescout-helpdesk/freescout#1999] opened 2022-05-16 06:01 UTC
It has now happened for the second time that an email in the inbox of the web server cannot be picked up by FreeScout. I am then notified myself by mail: "[FreeScout] Fetching Problems" and in the fetching logs there is several times the following entry: Folder: INBOX; Error: Unexpected characters at end of address: <> Maybe this ist not okay: **From: <""@syma.com.br>**

So far, I have always solved the problem by deleting the stuck email. Here, this is the problematic email (BTW: It is SPAM.):

![grafik](https://user-images.githubusercontent.com/3184297/168528366-429a0d62-1c0d-46f2-ad09-a72cddb71ac9.png)

And here is the header:

```

Return-Path: <MAILER-DAEMON>
X-Spam-Checker-Version: SpamAssassin 3.4.4 (2020-01-24) on r24.hallo.cloud
X-Spam-Level: *
X-Spam-Status: No, score=1.7 required=7.0 tests=BAYES_00,DKIM_SIGNED,
    DKIM_VALID,DKIM_VALID_AU,FREEMAIL_FORGED_REPLYTO,FSL_BULK_SIG,
    LOTS_OF_MONEY,MIME_QP_LONG_LINE,MONEY_FREEMAIL_REPTO,PYZOR_CHECK,
    SPF_HELO_NONE,SPF_NONE,TO_MALFORMED,T_SCC_BODY_TEXT_LINE,URIBL_BLOCKED
    autolearn=no autolearn_force=no version=3.4.4
X-Original-To: info@example.de
Delivered-To: info@example.de
Received: from zimbra.syma.com.br (zimbra.syma.com.br [177.125.218.238])
    by r24.example.cloud (Postfix) with ESMTPS id 4BE4A11DA2F0
    for <info@example.de>; Mon, 16 May 2022 07:19:48 +0200 (CEST)
Authentication-Results: r24;
    dkim=pass header.d=syma.com.br;
    spf=pass (sender IP is 177.125.218.238) smtp.mailfrom= smtp.helo=zimbra.syma.com.br
Received-SPF: pass (r24: domain of zimbra.syma.com.br designates 177.125.218.238 as permitted sender) client-ip=177.125.218.238; envelope-from=postmaster@zimbra.syma.com.br; helo=zimbra.syma.com.br;
Received: from zimbra.syma.com.br (localhost [127.0.0.1])
    by zimbra.syma.com.br (Postfix) with ESMTPS id E6C121D1A067;
    Sun, 15 May 2022 16:44:36 -0300 (-03)
Received: from localhost (localhost [127.0.0.1])
    by zimbra.syma.com.br (Postfix) with ESMTP id E58D71D01336;
    Sun, 15 May 2022 14:26:17 -0300 (-03)
DKIM-Filter: OpenDKIM Filter v2.10.3 zimbra.syma.com.br E58D71D01336
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=syma.com.br;
    s=9283041E-A02C-11E5-BA53-E41381C01A6E; t=1652635578;
    bh=+4W9bRDo2ePleagVm7pONp+mRBiOKbYQmZMgSciLL7M=;
    h=MIME-Version:To:From:Date:Message-Id;
    b=nV3DdatlTsyvY9Y5Abd41tbKQTXYFSjHoIBuhZhtru9zwALpwQWccpqefUZdCGVgL
    1q6mHSPBnUDQrfdGb0DOwMNXfGaZVrHiBbJ8+YddKSCdW8Ml7zmT4vvMuKbGEz992R
    GuhN6Sh5P2rhddR+lCybDaGedxA8bzPuS1ao6vJo=
X-Amavis-Modified: Mail body modified (using disclaimer) - zimbra.syma.com.br
X-Virus-Scanned: amavisd-new at syma.com.br
Received: from zimbra.syma.com.br ([127.0.0.1])
    by localhost (zimbra.syma.com.br [127.0.0.1]) (amavisd-new, port 10026)
    with ESMTP id LU4zzM_7mfA1; Sun, 15 May 2022 14:26:17 -0300 (-03)
Received: from [192.168.0.129] (unknown [212.102.49.20])
    by zimbra.syma.com.br (Postfix) with ESMTPSA id C43B01CA8723;
    Sun, 15 May 2022 12:39:01 -0300 (-03)
Content-Type: text/plain; charset="utf-8"
MIME-Version: 1.0
Content-Transfer-Encoding: quoted-printable
Content-Description: Mail message body
Subject: =?utf-8?q?N=C3=A4chster_Angeh=C3=B6riger?=
To: Recipients <>
From: <""@syma.com.br>
Date: Sun, 15 May 2022 16:38:38 +0100
Reply-To: mariyasingh@aliyun.com
Message-Id: <20220515153902.C43B01CA8723@zimbra.syma.com.br> 
```

**Comment by freescout-helpdesk** [comment] 2022-05-16 09:07
Are you using a modern Microsoft Exchange authentication or regular IMAP?

**Comment by Servery** [comment] 2022-05-16 21:13
Inbound regular IMAP SSL 993 (with Plesk)

**Comment by EliasPawlow** [comment] 2022-05-23 09:18
I hawe some error

**Comment by ololukaszuk** [comment] 2022-05-23 14:27
Same thing spotted in one of our instances, occured after an upgrade from 1.7.24 to 1.8.15.
Connection via IMAP/SMTP, sending works fine, recieving fails.
PHP 7.4.3

Tried restarting and clearing the cache (from GUI) to no avail.

Issue seems to clear after troublesome message (long To: list - 5 email addresses) has been marked as read on the mailserver.
But we had also an issue with "Folder: INBOX; Error: Unexpected characters at end of address: <no-reply@dhl.com>", so probably something else is in play.

**Comment by freescout-helpdesk** [comment] 2022-05-30 05:57
The issue has been fixed in the 1.8.16 release.

**Closed by freescout-helpdesk** 2022-05-30 05:57 UTC

**Comment by atakan72** [comment] 2023-02-16 18:43
every now and then i get the same error message 

`Error fetching email Folder: INBOX; Error: Unexpected characters at end of address: <info@mydomain.com>`

i also use IMAP SSL 993 (with Plesk)
i use docker with the latest version with the tag latest_php8.2

**Comment by mitchplze** [comment] 2023-10-20 19:11
I seem to get this once or twice a week randomly, too. On FreeScout v1.8.104 via the tiredofit Docker image, php 8.2.

`[2023-10-20 11:11:01] Error fetching email {"error":"Folder: INBOX; Error: Unexpected characters at end of address: <>","mailbox":"<RedactedMailboxName>"}`

**Comment by mitchplze** [comment] 2023-10-20 19:12
I also get this error randomly, too. On Freescout v1.8.104 via the tiredofit Docker image.

`[2023-10-20 11:11:01] Error fetching email {"error":"Folder: INBOX; Error: Unexpected characters at end of address: <>","mailbox":"My Mailbox Name"}`

**Comment by freescout-helpdesk** [comment] 2023-10-22 16:35
> I also get this error randomly, too. On Freescout v1.8.104 via the tiredofit Docker image.

Are you using modern Microsoft OAuth IMAP authentication or `APP_NEW_FETCHING_LIBRARY=true` parameter in .env file?

**Comment by mitchplze** [comment] 2023-10-22 16:42
> Are you using modern Microsoft OAuth IMAP authentication or `APP_NEW_FETCHING_LIBRARY=true` parameter in .env file?

Nope, neither. 

IMAP to a docker-mailserver container.
Standard db connect variables only.

**Comment by freescout-helpdesk** [comment] 2023-10-22 16:50
Set `APP_NEW_FETCHING_LIBRARY=true` in the .env file and clear the cache.

**Comment by mitchplze** [comment] 2023-10-24 20:47
> Set `APP_NEW_FETCHING_LIBRARY=true` in the .env file and clear the cache.

Ok, I've done that. As the issue is intermittent, I cannot test so I will continue to monitor and advise on this issue if it recurs.
