### ISSUE TITLE
The Kanban board does not show closed conversations

### ISSUE THREAD

**Issue by il2020** [freescout-helpdesk/freescout#3955] opened 2024-04-12 08:19 UTC
https://github.com/freescout-helpdesk/freescout/assets/77854832/b608198b-21bb-4388-a108-97fb66b86f89

PHP version: 8.2.7
FreeScout version: 1.8.130
Database: MySQL
Are you using CloudFlare: No

**Comment by freescout-helpdesk** [comment] 2024-04-12 08:29
We've can't reproduce the issue. Maybe there are some other filters hiding that conversation.

**Comment by il2020** [comment] 2024-04-12 08:36
Just state.

Are you trying to do that here? https://demo.freescout.net/kanban?kn[board_id]=1

<img width="1172" alt="Screenshot 2024-04-12 at 11 34 02" src="https://github.com/freescout-helpdesk/freescout/assets/77854832/90ffaaa4-af1c-4351-98d2-461596314a42">

**Comment by freescout-helpdesk** [comment] 2024-04-12 09:00
Test it on your own FreeScout instance of the latest version. On Demo there may be different Workflows configured changing Status of the conversation or deleting it.

**Comment by il2020** [comment] 2024-04-12 09:20
The thing is, I noticed this problem on my own FreeScout instance and came to check in Demo. If the conversation is active or pending, it is visible on the board. As soon as I close the conversation, it disappears from the board. I don't understand why it works differently for you.

**Comment by freescout-helpdesk** [comment] 2024-04-12 12:56
Fixed in Kanban Module v1.0.22. Now "Active" and "Pending" statuses will be selected by default in the Status filter.

**Closed** 2024-04-13 06:51 UTC
