### ISSUE TITLE
Saving drafts duplicates attachments

### ISSUE THREAD

**Issue by cf39** [freescout-helpdesk/freescout#1186] opened 2021-04-28 18:22 UTC
When saving a draft with an attachment, if the draft is reopened the attachment is duplicated.

**Comment by fulldecent** [comment] 2021-07-09 16:37
duplicate of issue #1004. recommending close

**Comment by freescout-helpdesk** [comment] 2021-07-11 05:44
Fixed in FreeScout v1.7.12

**Closed by freescout-helpdesk** 2021-07-11 05:44 UTC
Labels: help wanted
