### ISSUE TITLE
Bug? Feature? | Signature Mode "Raw Html" mode doesn't save properly

### ISSUE THREAD

**Issue by tiredofit** [freescout-helpdesk/freescout#673] opened 2020-07-14 23:27 UTC
I noticed when editing a Signature for a mailbox and switching to Raw HTML Mode. You are unable to save the message properly. Upon page reload the signature is blank. It will only save when clicking out of Raw HTML mode will it save the contents of the message. Perhaps this is a bug with one of the Laravel modules.

**Comment by NedScott** [comment] 2022-08-11 00:05
See https://github.com/freescout-helpdesk/freescout/issues/1705 which might have a possible solution

**Comment by freescout-helpdesk** [comment] 2022-12-19 14:11
Duplicate of https://github.com/freescout-helpdesk/freescout/issues/1705

**Closed by freescout-helpdesk** 2022-12-19 14:11 UTC
Labels: help wanted
