### ISSUE TITLE
Unwanted Notifications Issue After FreeScout Update to Version 1.8.115

### ISSUE THREAD

**Issue by NaveenKharwar** [freescout-helpdesk/freescout#3663] opened 2024-01-08 07:18 UTC
Hi team,

I'm Naveen from the Brainstorm Force team. After updating FreeScout to version 1.8.115, we've encountered an issue where all our agents are receiving notifications for tickets they haven't contributed to. For instance, Agent A is getting notifications for Ticket `1234` even though they haven't participated in that ticket.

Previously, before the update, agents only received notifications for new replies if they had contributed to the ticket. Notifications were limited to user replies, and agent replies did not trigger notifications.

We appreciate your assistance in resolving this matter.

Additional Information:

- **PHP version:** 7.4.33
- **FreeScout version:** 1.8.115
- **Database:** MySQL (5.5.5-10.11.6-MariaDB-1:10.11.6+maria~ubu2204)
- **CloudFlare usage:** No

**Comment by freescout-helpdesk** [comment] 2024-01-10 11:24
It's hard to tell why it happens for you. Try to share screenshot of some user's notification settings.

**Comment by NaveenKharwar** [comment] 2024-01-16 13:50
> It's hard to tell why it happens for you. Try to share screenshot of some user's notification settings.

This screenshot will provide a better understanding of the issue. You can view the screenshot [here](https://bsf.d.pr/i/9XePmL).

Previously, I used to only receive notifications for tickets to which I had ever replied / involved .

**Comment by freescout-helpdesk** [comment] 2024-01-20 08:07
Unfortunately we can't reproduce the issue.

**Comment by NaveenKharwar** [comment] 2024-01-23 03:55
We upgraded the Freescout to version 1.8.118, the issue still persists. Could you please try again to reproduce and assist us in resolving this problem?

PS: We noticed the issue after upgrading Freescout to 1.8.115 +

**Comment by freescout-helpdesk** [comment] 2024-01-25 06:28
It looks like you are the only one having this issue so far. Maybe some settings are set on your FreeScout causing this of which we are not aware yet.

We'll close this for now and wait if there will be more similar bug reports.

**Closed by freescout-helpdesk** 2024-01-25 06:28 UTC
