### ISSUE TITLE
9 Custom folders and My tickets changes in position...

### ISSUE THREAD

**Issue by joris85** [freescout-helpdesk/freescout#583] opened 2020-04-18 09:42 UTC
Voor mij (My tickets) changes from position in the menu if i add more than 8 custom folders :-)

Normal:
https://www.dropbox.com/s/wo6phfi10nfo1ls/Schermafdruk%202020-04-18%2011.40.24.png?dl=0

With 1 extra custom folder:
https://www.dropbox.com/s/cjhdw8rkljiep5h/Schermafdruk%202020-04-18%2011.40.00.png?dl=0

**Comment by freescout-helpdesk** [comment] 2020-04-18 09:46
Will be fixed.

**Comment by freescout-helpdesk** [comment] 2020-07-26 13:15
Sorry, we could not reproduce the issue. You may need to find the reason by yourself.

**Comment by freescout-helpdesk** [comment] 2020-08-27 12:25
Closing for no activity.

**Closed by freescout-helpdesk** 2020-08-27 12:25 UTC
