### ISSUE TITLE
After switching to Chinese Simplify, editing tickets doesn't work properly

### ISSUE THREAD

**Issue by jeffrey4680** [freescout-helpdesk/freescout#3303] opened 2023-08-25 07:25 UTC
PHP version: 8.2
FreeScout version:  1.8.93

As the screeshot shows, when switching the language to Chinese Simplify, editing tickets such as modifying or adding a task, adding or removing tags, assigning another agent change ticket status etc. doesn't work but it works with English app setting. please check this following screenshot  https://screenrec.com/share/H2hI46ifPa  Thank you so much

**Comment by freescout-helpdesk** [comment] 2023-08-25 13:30
We can't reproduce the issue.

Apparently JavaScript gets broken for you in Chinese language. Check errors in the browser console.

Try to update FreeScout to the latest version or update FreeScout using manual updating method: https://github.com/freescout-helpdesk/freescout/wiki/Updating-FreeScout#method-5-update-manually

**Comment by jeffrey4680** [comment] 2023-08-25 16:03
I have removed vendor directory and updated freescout plugin and then cleared cache already, unfortunately that issue still persists. it was probably caused by module translate script as well I guess, you can try to log in to the admin area with credentials username: ***@***.***  password: dobio1010  at  https://kids.dobio.com/login for the details checking. Thanks,
Jeffrey
https://kids.dobio.com/conversation/3?folder_id=10#
________________________________

**Comment by freescout-helpdesk** [comment] 2023-08-25 17:23
> Check errors in the browser console.

**Comment by jeffrey4680** [comment] 2023-08-25 23:21
I just created a sftp for debugging purpose for you. You now have access to web code by credentials below
Public ip: 24.199.124.235
Username: freescoutsupport
Password: 23wewwrw23234wA

I have fully made a staging site for that so that you can debug it until I get a response from you. You cannot reproduce this issue because I have completely translated all modules to Chinese simplify, for accuracy considering, I didn't send the copy to you.

Best,
Jeffrey
________________________________

**Comment by freescout-helpdesk** [comment] 2023-08-26 04:46
You'll need to debug the issue yourself or find someone who can do it for you (https://github.com/freescout-helpdesk/freescout/wiki/Hire-Developer).

Also see troubleshooting: https://github.com/freescout-helpdesk/freescout/wiki/Installation-Guide#11-troubleshooting

And feel free to send all the translations - maybe we'll be able to reproduce the issue.

**Comment by jeffrey4680** [comment] 2023-08-26 04:54
Of course, please check the attached zip file including all the translated Chinese scripts. Thanks,
Jeffrey
________________________________

**Comment by freescout-helpdesk** [comment] 2023-08-26 05:11
The attachment is missing. Here is how to send translations properly: https://github.com/freescout-helpdesk/freescout/wiki/Translate

**Comment by jeffrey4680** [comment] 2023-08-26 05:17
Please check the attached zip file again, before I attached it, I have checked the file completion, all chinese scripts included it.
________________________________

**Comment by freescout-helpdesk** [comment] 2023-08-26 05:32
The attachment is still missing.

**Comment by jeffrey4680** [comment] 2023-08-26 05:35
[https://res.cdn.office.net/assets/mail/file-icon/png/zip_16x16.png]lang (1).zip<https://1drv.ms/u/s!AggL5PK-AeXTrBcvQsXMdtMlVeKn>
Sorry to hear about this, let me give it a try again, if you cannot get it again, I will try to send this with my gmail account.
Best,
Jeffrey
________________________________

**Comment by freescout-helpdesk** [comment] 2023-08-26 07:34
We've applied translations. The problem was in Noreply Emails Module. Fixed in Noreply Emails Module v1.0.7

**Comment by jeffrey4680** [comment] 2023-08-26 08:40
Yes, it is working great now. Thank you so much  :)
________________________________

**Closed** 2023-08-26 09:23 UTC
