### ISSUE TITLE
Improper file renaming when there's two dots at the end of the file name

### ISSUE THREAD

**Issue by mattly6** [freescout-helpdesk/freescout#3592] opened 2023-12-07 19:10 UTC
Hi, I noticed an unwanted behavior when downloading attachments from customers that contain a dot at the end.
Instead of receiving a sent DummyFile..pdf, I get DummyFilepdf - all dots get removed and the file has to be renamed after downloading to function properly.

To reproduce, you basically need to send yourself such a file - below is the file I sent, above the one I got after downloading the message from the server:
![image](https://github.com/freescout-helpdesk/freescout/assets/61761426/637feb33-071e-4909-9b22-0cb330212985) 

FreeScout version: 1.8.110

**Comment by freescout-helpdesk** [comment] 2023-12-08 05:29
We can't reproduce the issue. Can you reproduce it on demo.freescout.net and send a link to conversation.

**Comment by mattly6** [comment] 2023-12-08 15:14
> We can't reproduce the issue. Can you reproduce it on demo.freescout.net and send a link to conversation.

Hi, I managed to reproduce the issue.
https://demo.freescout.net/conversation/48?folder_id=350

**Comment by freescout-helpdesk** [comment] 2023-12-09 18:41
Fixed in the `master` branch and will be published in the next release.

**Closed** 2023-12-15 07:58 UTC
