### ISSUE TITLE
Multiple issues with attachment in drafts

### ISSUE THREAD

**Issue by martin3mf** [freescout-helpdesk/freescout#1004] opened 2021-01-17 22:08 UTC
1. When refreshing a draft, the attachments are duplicated. This results in a large amount of attachment files.
2. New attachments have no thread id after refreshing the draft
3. Deleting an attachment in the draft just hides the attachment with js, the attachment is neither deleted in the database nor deleted from the file system.

**Comment by radarsymphony** [comment] 2021-02-25 21:31
Hi @martin3mf  & @freescout-helpdesk,
We were able to replicate this issue on our system as well as in a Freescout Demo account. 
This issue also seems to be related to issue #967 submitted by @Filoz 
Below is a description of what we noticed:

## Summary
Conversations with attachments that are saved to Drafts and then reopened have duplicate attachments. The number of attachments follows this series (1), 2, 4, 8, 16, etc

## Steps to reproduce
1. Within a mailbox, open a new conversation.
2. Add recipient email, subject, body text, and attachment (e.g., PDF).
3. Click away from this conversation.** As per example image below, click on 'Unassigned' (1) and then back to 'Drafts' (2). 
4. Open the draft just created and note number of attachments (should still be 1).
5. Click back to 'Unassigned' (or similar) and return to 'Drafts' and reopen that same draft.**
6. Note number of attachments (should be 2 now)
7. Repeat steps 5-6, noting number of attachment duplicates doubling on each open. 
 
** as @martin3mf describes, refreshing the draft also duplicates the attachment
> When refreshing a draft, the attachments are duplicated. This results in a large amount of attachment files.

![image](https://user-images.githubusercontent.com/73671474/109219859-07be8880-776d-11eb-95ca-2cc40bb26b08.png)

## What is the current bug behavior?
The issue seems to occur regardless of attachment type. Removing duplicates before saving conversation as a Draft does not seem to interrupt the duplicate accrual [i.e., (1), 2, 4 (-3), 8 (not 2 again) ].

**Comment by freescout-helpdesk** [comment] 2021-07-11 05:44
Fixed in FreeScout v1.7.12

**Closed by freescout-helpdesk** 2021-07-11 05:44 UTC
Labels: help wanted
