### ISSUE TITLE
Cronjob via link not working

### ISSUE THREAD

**Issue by Hamza31231** [freescout-helpdesk/freescout#4001] opened 2024-04-26 13:30 UTC
Hi,

I found a problem on new version:
after Update to version 1.8.137 of freescout the automatic mail fetching stopped working.
On ssh i can run the fetch:mail and it works but using the link it does not work any more.
By using the link, freescout says: "No scheduled commands are ready to run."
My hoster only allows to run cron jobs using link. So at the moment I have the big problem that fetching mail automaticly
stopped.

Is this a bug? What can I do to solve it?
I checket the logs, no error on this found.

**Comment by Hamza31231** [comment] 2024-04-26 13:31
![image](https://github.com/freescout-helpdesk/freescout/assets/46626926/bed1f543-f622-478a-9954-1263960a42dc)

**Comment by Hamza31231** [comment] 2024-04-26 13:32
![image](https://github.com/freescout-helpdesk/freescout/assets/46626926/7ba86483-7893-4e4e-b201-f0fbc0251e52)

**Comment by Hamza31231** [comment] 2024-04-26 13:34
the queue is full with mails to send
recieving mails stopps

after performin the ssh action artisan schedule:run it is working one time then it stops again because cron job via link does not do anything

please help

**Comment by Hamza31231** [comment] 2024-04-26 13:36
i think the link is broken after update
how to check?

**Comment by Hamza31231** [comment] 2024-04-26 13:37
UPDATE:

now I have updated the next instance of freescout and have the same problem !
this looks like a bug in the newest version

please help

**Comment by freescout-helpdesk** [comment] 2024-04-26 13:38
Duplicate of https://github.com/freescout-helpdesk/freescout/issues/4000

**Closed by freescout-helpdesk** 2024-04-26 13:38 UTC
